package com.google.mediapipe.tasks.text.textclassifier;

import com.google.mediapipe.tasks.components.containers.ClassificationResult;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_TextClassifierResult extends TextClassifierResult {

  private final ClassificationResult classificationResult;

  private final long timestampMs;

  AutoValue_TextClassifierResult(
      ClassificationResult classificationResult,
      long timestampMs) {
    if (classificationResult == null) {
      throw new NullPointerException("Null classificationResult");
    }
    this.classificationResult = classificationResult;
    this.timestampMs = timestampMs;
  }

  @Override
  public ClassificationResult classificationResult() {
    return classificationResult;
  }

  @Override
  public long timestampMs() {
    return timestampMs;
  }

  @Override
  public String toString() {
    return "TextClassifierResult{"
        + "classificationResult=" + classificationResult + ", "
        + "timestampMs=" + timestampMs
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof TextClassifierResult) {
      TextClassifierResult that = (TextClassifierResult) o;
      return this.classificationResult.equals(that.classificationResult())
          && this.timestampMs == that.timestampMs();
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= classificationResult.hashCode();
    h$ *= 1000003;
    h$ ^= (int) ((timestampMs >>> 32) ^ timestampMs);
    return h$;
  }

}
