// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/core/proto/acceleration.proto

package com.google.mediapipe.tasks.core.proto;

public final class AccelerationProto {
  private AccelerationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AccelerationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.core.proto.Acceleration)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     * @return Whether the xnnpack field is set.
     */
    boolean hasXnnpack();
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     * @return The xnnpack.
     */
    com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack getXnnpack();

    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     * @return Whether the gpu field is set.
     */
    boolean hasGpu();
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     * @return The gpu.
     */
    com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu getGpu();

    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     * @return Whether the tflite field is set.
     */
    boolean hasTflite();
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     * @return The tflite.
     */
    com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite getTflite();

    public Acceleration.DelegateCase getDelegateCase();
  }
  /**
   * <pre>
   * TODO Enable Automatic mode once it is ready.
   * </pre>
   *
   * Protobuf type {@code mediapipe.tasks.core.proto.Acceleration}
   */
  public  static final class Acceleration extends
      com.google.protobuf.GeneratedMessageLite<
          Acceleration, Acceleration.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.core.proto.Acceleration)
      AccelerationOrBuilder {
    private Acceleration() {
    }
    private int bitField0_;
    private int delegateCase_ = 0;
    private Object delegate_;
    public enum DelegateCase {
      XNNPACK(1),
      GPU(2),
      TFLITE(4),
      DELEGATE_NOT_SET(0);
      private final int value;
      private DelegateCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DelegateCase valueOf(int value) {
        return forNumber(value);
      }

      public static DelegateCase forNumber(int value) {
        switch (value) {
          case 1: return XNNPACK;
          case 2: return GPU;
          case 4: return TFLITE;
          case 0: return DELEGATE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public DelegateCase
    getDelegateCase() {
      return DelegateCase.forNumber(
          delegateCase_);
    }

    private void clearDelegate() {
      delegateCase_ = 0;
      delegate_ = null;
    }

    public static final int XNNPACK_FIELD_NUMBER = 1;
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     */
    @Override
    public boolean hasXnnpack() {
      return delegateCase_ == 1;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     */
    @Override
    public com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack getXnnpack() {
      if (delegateCase_ == 1) {
         return (com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack) delegate_;
      }
      return com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack.getDefaultInstance();
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     */
    private void setXnnpack(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack value) {
      value.getClass();
  delegate_ = value;
      delegateCase_ = 1;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     */
    private void mergeXnnpack(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack value) {
      value.getClass();
  if (delegateCase_ == 1 &&
          delegate_ != com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack.getDefaultInstance()) {
        delegate_ = com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack.newBuilder((com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack) delegate_)
            .mergeFrom(value).buildPartial();
      } else {
        delegate_ = value;
      }
      delegateCase_ = 1;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
     */
    private void clearXnnpack() {
      if (delegateCase_ == 1) {
        delegateCase_ = 0;
        delegate_ = null;
      }
    }

    public static final int GPU_FIELD_NUMBER = 2;
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     */
    @Override
    public boolean hasGpu() {
      return delegateCase_ == 2;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     */
    @Override
    public com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu getGpu() {
      if (delegateCase_ == 2) {
         return (com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu) delegate_;
      }
      return com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu.getDefaultInstance();
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     */
    private void setGpu(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu value) {
      value.getClass();
  delegate_ = value;
      delegateCase_ = 2;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     */
    private void mergeGpu(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu value) {
      value.getClass();
  if (delegateCase_ == 2 &&
          delegate_ != com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu.getDefaultInstance()) {
        delegate_ = com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu.newBuilder((com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu) delegate_)
            .mergeFrom(value).buildPartial();
      } else {
        delegate_ = value;
      }
      delegateCase_ = 2;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
     */
    private void clearGpu() {
      if (delegateCase_ == 2) {
        delegateCase_ = 0;
        delegate_ = null;
      }
    }

    public static final int TFLITE_FIELD_NUMBER = 4;
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     */
    @Override
    public boolean hasTflite() {
      return delegateCase_ == 4;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     */
    @Override
    public com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite getTflite() {
      if (delegateCase_ == 4) {
         return (com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite) delegate_;
      }
      return com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite.getDefaultInstance();
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     */
    private void setTflite(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite value) {
      value.getClass();
  delegate_ = value;
      delegateCase_ = 4;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     */
    private void mergeTflite(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite value) {
      value.getClass();
  if (delegateCase_ == 4 &&
          delegate_ != com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite.getDefaultInstance()) {
        delegate_ = com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite.newBuilder((com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite) delegate_)
            .mergeFrom(value).buildPartial();
      } else {
        delegate_ = value;
      }
      delegateCase_ = 4;
    }
    /**
     * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
     */
    private void clearTflite() {
      if (delegateCase_ == 4) {
        delegateCase_ = 0;
        delegate_ = null;
      }
    }

    public static Acceleration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Acceleration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Acceleration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Acceleration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Acceleration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Acceleration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Acceleration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Acceleration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Acceleration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Acceleration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Acceleration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Acceleration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Acceleration prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * TODO Enable Automatic mode once it is ready.
     * </pre>
     *
     * Protobuf type {@code mediapipe.tasks.core.proto.Acceleration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Acceleration, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.core.proto.Acceleration)
        AccelerationOrBuilder {
      // Construct using com.google.mediapipe.tasks.core.proto.AccelerationProto.Acceleration.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public DelegateCase
          getDelegateCase() {
        return instance.getDelegateCase();
      }

      public Builder clearDelegate() {
        copyOnWrite();
        instance.clearDelegate();
        return this;
      }


      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
       */
      @Override
      public boolean hasXnnpack() {
        return instance.hasXnnpack();
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
       */
      @Override
      public com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack getXnnpack() {
        return instance.getXnnpack();
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
       */
      public Builder setXnnpack(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack value) {
        copyOnWrite();
        instance.setXnnpack(value);
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
       */
      public Builder setXnnpack(
          com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack.Builder builderForValue) {
        copyOnWrite();
        instance.setXnnpack(builderForValue.build());
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
       */
      public Builder mergeXnnpack(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack value) {
        copyOnWrite();
        instance.mergeXnnpack(value);
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Xnnpack xnnpack = 1;</code>
       */
      public Builder clearXnnpack() {
        copyOnWrite();
        instance.clearXnnpack();
        return this;
      }

      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
       */
      @Override
      public boolean hasGpu() {
        return instance.hasGpu();
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
       */
      @Override
      public com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu getGpu() {
        return instance.getGpu();
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
       */
      public Builder setGpu(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu value) {
        copyOnWrite();
        instance.setGpu(value);
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
       */
      public Builder setGpu(
          com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu.Builder builderForValue) {
        copyOnWrite();
        instance.setGpu(builderForValue.build());
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
       */
      public Builder mergeGpu(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu value) {
        copyOnWrite();
        instance.mergeGpu(value);
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.Gpu gpu = 2;</code>
       */
      public Builder clearGpu() {
        copyOnWrite();
        instance.clearGpu();
        return this;
      }

      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
       */
      @Override
      public boolean hasTflite() {
        return instance.hasTflite();
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
       */
      @Override
      public com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite getTflite() {
        return instance.getTflite();
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
       */
      public Builder setTflite(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite value) {
        copyOnWrite();
        instance.setTflite(value);
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
       */
      public Builder setTflite(
          com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite.Builder builderForValue) {
        copyOnWrite();
        instance.setTflite(builderForValue.build());
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
       */
      public Builder mergeTflite(com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite value) {
        copyOnWrite();
        instance.mergeTflite(value);
        return this;
      }
      /**
       * <code>.mediapipe.InferenceCalculatorOptions.Delegate.TfLite tflite = 4;</code>
       */
      public Builder clearTflite() {
        copyOnWrite();
        instance.clearTflite();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.core.proto.Acceleration)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Acceleration();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "delegate_",
              "delegateCase_",
              "bitField0_",
              com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Xnnpack.class,
              com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.Gpu.class,
              com.google.mediapipe.calculator.proto.InferenceCalculatorProto.InferenceCalculatorOptions.Delegate.TfLite.class,
            };
            String info =
                "\u0001\u0003\u0001\u0001\u0001\u0004\u0003\u0000\u0000\u0000\u0001\u103c\u0000\u0002" +
                "\u103c\u0000\u0004\u103c\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Acceleration> parser = PARSER;
          if (parser == null) {
            synchronized (Acceleration.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Acceleration>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.core.proto.Acceleration)
    private static final Acceleration DEFAULT_INSTANCE;
    static {
      Acceleration defaultInstance = new Acceleration();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Acceleration.class, defaultInstance);
    }

    public static Acceleration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Acceleration> PARSER;

    public static com.google.protobuf.Parser<Acceleration> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
