// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/components/containers/proto/embeddings.proto

package com.google.mediapipe.tasks.components.containers.proto;

public final class EmbeddingsProto {
  private EmbeddingsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FloatEmbeddingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.components.containers.proto.FloatEmbedding)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @return A list containing the values.
     */
    java.util.List<Float> getValuesList();
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @return The count of values.
     */
    int getValuesCount();
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    float getValues(int index);
  }
  /**
   * <pre>
   * Defines a dense floating-point embedding.
   * </pre>
   *
   * Protobuf type {@code mediapipe.tasks.components.containers.proto.FloatEmbedding}
   */
  public  static final class FloatEmbedding extends
      com.google.protobuf.GeneratedMessageLite<
          FloatEmbedding, FloatEmbedding.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.components.containers.proto.FloatEmbedding)
      FloatEmbeddingOrBuilder {
    private FloatEmbedding() {
      values_ = emptyFloatList();
    }
    public static final int VALUES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList values_;
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @return A list containing the values.
     */
    @Override
    public java.util.List<Float>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @return The count of values.
     */
    @Override
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    @Override
    public float getValues(int index) {
      return values_.getFloat(index);
    }
    private int valuesMemoizedSerializedSize = -1;
    private void ensureValuesIsMutable() {
      com.google.protobuf.Internal.FloatList tmp = values_;
      if (!tmp.isModifiable()) {
        values_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The values to set.
     */
    private void setValues(
        int index, float value) {
      ensureValuesIsMutable();
      values_.setFloat(index, value);
    }
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @param value The values to add.
     */
    private void addValues(float value) {
      ensureValuesIsMutable();
      values_.addFloat(value);
    }
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     * @param values The values to add.
     */
    private void addAllValues(
        Iterable<? extends Float> values) {
      ensureValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, values_);
    }
    /**
     * <code>repeated float values = 1 [packed = true];</code>
     */
    private void clearValues() {
      values_ = emptyFloatList();
    }

    public static FloatEmbedding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FloatEmbedding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FloatEmbedding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FloatEmbedding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FloatEmbedding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FloatEmbedding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FloatEmbedding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FloatEmbedding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FloatEmbedding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static FloatEmbedding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FloatEmbedding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FloatEmbedding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(FloatEmbedding prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Defines a dense floating-point embedding.
     * </pre>
     *
     * Protobuf type {@code mediapipe.tasks.components.containers.proto.FloatEmbedding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FloatEmbedding, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.components.containers.proto.FloatEmbedding)
        FloatEmbeddingOrBuilder {
      // Construct using com.google.mediapipe.tasks.components.containers.proto.EmbeddingsProto.FloatEmbedding.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @return A list containing the values.
       */
      @Override
      public java.util.List<Float>
          getValuesList() {
        return java.util.Collections.unmodifiableList(
            instance.getValuesList());
      }
      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @return The count of values.
       */
      @Override
      public int getValuesCount() {
        return instance.getValuesCount();
      }
      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      @Override
      public float getValues(int index) {
        return instance.getValues(index);
      }
      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @param value The values to set.
       * @return This builder for chaining.
       */
      public Builder setValues(
          int index, float value) {
        copyOnWrite();
        instance.setValues(index, value);
        return this;
      }
      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @param value The values to add.
       * @return This builder for chaining.
       */
      public Builder addValues(float value) {
        copyOnWrite();
        instance.addValues(value);
        return this;
      }
      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @param values The values to add.
       * @return This builder for chaining.
       */
      public Builder addAllValues(
          Iterable<? extends Float> values) {
        copyOnWrite();
        instance.addAllValues(values);
        return this;
      }
      /**
       * <code>repeated float values = 1 [packed = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearValues() {
        copyOnWrite();
        instance.clearValues();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.components.containers.proto.FloatEmbedding)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new FloatEmbedding();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "values_",
            };
            String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001$";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<FloatEmbedding> parser = PARSER;
          if (parser == null) {
            synchronized (FloatEmbedding.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<FloatEmbedding>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.components.containers.proto.FloatEmbedding)
    private static final FloatEmbedding DEFAULT_INSTANCE;
    static {
      FloatEmbedding defaultInstance = new FloatEmbedding();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FloatEmbedding.class, defaultInstance);
    }

    public static FloatEmbedding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FloatEmbedding> PARSER;

    public static com.google.protobuf.Parser<FloatEmbedding> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface QuantizedEmbeddingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.components.containers.proto.QuantizedEmbedding)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes values = 1;</code>
     * @return Whether the values field is set.
     */
    boolean hasValues();
    /**
     * <code>optional bytes values = 1;</code>
     * @return The values.
     */
    com.google.protobuf.ByteString getValues();
  }
  /**
   * <pre>
   * Defines a dense scalar-quantized embedding.
   * </pre>
   *
   * Protobuf type {@code mediapipe.tasks.components.containers.proto.QuantizedEmbedding}
   */
  public  static final class QuantizedEmbedding extends
      com.google.protobuf.GeneratedMessageLite<
          QuantizedEmbedding, QuantizedEmbedding.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.components.containers.proto.QuantizedEmbedding)
      QuantizedEmbeddingOrBuilder {
    private QuantizedEmbedding() {
      values_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int VALUES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString values_;
    /**
     * <code>optional bytes values = 1;</code>
     * @return Whether the values field is set.
     */
    @Override
    public boolean hasValues() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes values = 1;</code>
     * @return The values.
     */
    @Override
    public com.google.protobuf.ByteString getValues() {
      return values_;
    }
    /**
     * <code>optional bytes values = 1;</code>
     * @param value The values to set.
     */
    private void setValues(com.google.protobuf.ByteString value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      values_ = value;
    }
    /**
     * <code>optional bytes values = 1;</code>
     */
    private void clearValues() {
      bitField0_ = (bitField0_ & ~0x00000001);
      values_ = getDefaultInstance().getValues();
    }

    public static QuantizedEmbedding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static QuantizedEmbedding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static QuantizedEmbedding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static QuantizedEmbedding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static QuantizedEmbedding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static QuantizedEmbedding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static QuantizedEmbedding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static QuantizedEmbedding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static QuantizedEmbedding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static QuantizedEmbedding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static QuantizedEmbedding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static QuantizedEmbedding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(QuantizedEmbedding prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Defines a dense scalar-quantized embedding.
     * </pre>
     *
     * Protobuf type {@code mediapipe.tasks.components.containers.proto.QuantizedEmbedding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          QuantizedEmbedding, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.components.containers.proto.QuantizedEmbedding)
        QuantizedEmbeddingOrBuilder {
      // Construct using com.google.mediapipe.tasks.components.containers.proto.EmbeddingsProto.QuantizedEmbedding.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes values = 1;</code>
       * @return Whether the values field is set.
       */
      @Override
      public boolean hasValues() {
        return instance.hasValues();
      }
      /**
       * <code>optional bytes values = 1;</code>
       * @return The values.
       */
      @Override
      public com.google.protobuf.ByteString getValues() {
        return instance.getValues();
      }
      /**
       * <code>optional bytes values = 1;</code>
       * @param value The values to set.
       * @return This builder for chaining.
       */
      public Builder setValues(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValues(value);
        return this;
      }
      /**
       * <code>optional bytes values = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValues() {
        copyOnWrite();
        instance.clearValues();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.components.containers.proto.QuantizedEmbedding)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new QuantizedEmbedding();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "values_",
            };
            String info =
                "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u100a\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<QuantizedEmbedding> parser = PARSER;
          if (parser == null) {
            synchronized (QuantizedEmbedding.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<QuantizedEmbedding>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.components.containers.proto.QuantizedEmbedding)
    private static final QuantizedEmbedding DEFAULT_INSTANCE;
    static {
      QuantizedEmbedding defaultInstance = new QuantizedEmbedding();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        QuantizedEmbedding.class, defaultInstance);
    }

    public static QuantizedEmbedding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<QuantizedEmbedding> PARSER;

    public static com.google.protobuf.Parser<QuantizedEmbedding> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EmbeddingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.components.containers.proto.Embedding)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     * @return Whether the floatEmbedding field is set.
     */
    boolean hasFloatEmbedding();
    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     * @return The floatEmbedding.
     */
    FloatEmbedding getFloatEmbedding();

    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     * @return Whether the quantizedEmbedding field is set.
     */
    boolean hasQuantizedEmbedding();
    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     * @return The quantizedEmbedding.
     */
    QuantizedEmbedding getQuantizedEmbedding();

    /**
     * <pre>
     * The index of the embedder head that produced this embedding. This is useful
     * for multi-head models.
     * </pre>
     *
     * <code>optional int32 head_index = 3;</code>
     * @return Whether the headIndex field is set.
     */
    boolean hasHeadIndex();
    /**
     * <pre>
     * The index of the embedder head that produced this embedding. This is useful
     * for multi-head models.
     * </pre>
     *
     * <code>optional int32 head_index = 3;</code>
     * @return The headIndex.
     */
    int getHeadIndex();

    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @return Whether the headName field is set.
     */
    boolean hasHeadName();
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @return The headName.
     */
    String getHeadName();
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @return The bytes for headName.
     */
    com.google.protobuf.ByteString
        getHeadNameBytes();

    public Embedding.EmbeddingCase getEmbeddingCase();
  }
  /**
   * <pre>
   * Embedding result for a given embedder head.
   * </pre>
   *
   * Protobuf type {@code mediapipe.tasks.components.containers.proto.Embedding}
   */
  public  static final class Embedding extends
      com.google.protobuf.GeneratedMessageLite<
          Embedding, Embedding.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.components.containers.proto.Embedding)
      EmbeddingOrBuilder {
    private Embedding() {
      headName_ = "";
    }
    private int bitField0_;
    private int embeddingCase_ = 0;
    private Object embedding_;
    public enum EmbeddingCase {
      FLOAT_EMBEDDING(1),
      QUANTIZED_EMBEDDING(2),
      EMBEDDING_NOT_SET(0);
      private final int value;
      private EmbeddingCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static EmbeddingCase valueOf(int value) {
        return forNumber(value);
      }

      public static EmbeddingCase forNumber(int value) {
        switch (value) {
          case 1: return FLOAT_EMBEDDING;
          case 2: return QUANTIZED_EMBEDDING;
          case 0: return EMBEDDING_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public EmbeddingCase
    getEmbeddingCase() {
      return EmbeddingCase.forNumber(
          embeddingCase_);
    }

    private void clearEmbedding() {
      embeddingCase_ = 0;
      embedding_ = null;
    }

    public static final int FLOAT_EMBEDDING_FIELD_NUMBER = 1;
    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     */
    @Override
    public boolean hasFloatEmbedding() {
      return embeddingCase_ == 1;
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     */
    @Override
    public FloatEmbedding getFloatEmbedding() {
      if (embeddingCase_ == 1) {
         return (FloatEmbedding) embedding_;
      }
      return FloatEmbedding.getDefaultInstance();
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     */
    private void setFloatEmbedding(FloatEmbedding value) {
      value.getClass();
  embedding_ = value;
      embeddingCase_ = 1;
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     */
    private void mergeFloatEmbedding(FloatEmbedding value) {
      value.getClass();
  if (embeddingCase_ == 1 &&
          embedding_ != FloatEmbedding.getDefaultInstance()) {
        embedding_ = FloatEmbedding.newBuilder((FloatEmbedding) embedding_)
            .mergeFrom(value).buildPartial();
      } else {
        embedding_ = value;
      }
      embeddingCase_ = 1;
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
     */
    private void clearFloatEmbedding() {
      if (embeddingCase_ == 1) {
        embeddingCase_ = 0;
        embedding_ = null;
      }
    }

    public static final int QUANTIZED_EMBEDDING_FIELD_NUMBER = 2;
    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     */
    @Override
    public boolean hasQuantizedEmbedding() {
      return embeddingCase_ == 2;
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     */
    @Override
    public QuantizedEmbedding getQuantizedEmbedding() {
      if (embeddingCase_ == 2) {
         return (QuantizedEmbedding) embedding_;
      }
      return QuantizedEmbedding.getDefaultInstance();
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     */
    private void setQuantizedEmbedding(QuantizedEmbedding value) {
      value.getClass();
  embedding_ = value;
      embeddingCase_ = 2;
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     */
    private void mergeQuantizedEmbedding(QuantizedEmbedding value) {
      value.getClass();
  if (embeddingCase_ == 2 &&
          embedding_ != QuantizedEmbedding.getDefaultInstance()) {
        embedding_ = QuantizedEmbedding.newBuilder((QuantizedEmbedding) embedding_)
            .mergeFrom(value).buildPartial();
      } else {
        embedding_ = value;
      }
      embeddingCase_ = 2;
    }
    /**
     * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
     */
    private void clearQuantizedEmbedding() {
      if (embeddingCase_ == 2) {
        embeddingCase_ = 0;
        embedding_ = null;
      }
    }

    public static final int HEAD_INDEX_FIELD_NUMBER = 3;
    private int headIndex_;
    /**
     * <pre>
     * The index of the embedder head that produced this embedding. This is useful
     * for multi-head models.
     * </pre>
     *
     * <code>optional int32 head_index = 3;</code>
     * @return Whether the headIndex field is set.
     */
    @Override
    public boolean hasHeadIndex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The index of the embedder head that produced this embedding. This is useful
     * for multi-head models.
     * </pre>
     *
     * <code>optional int32 head_index = 3;</code>
     * @return The headIndex.
     */
    @Override
    public int getHeadIndex() {
      return headIndex_;
    }
    /**
     * <pre>
     * The index of the embedder head that produced this embedding. This is useful
     * for multi-head models.
     * </pre>
     *
     * <code>optional int32 head_index = 3;</code>
     * @param value The headIndex to set.
     */
    private void setHeadIndex(int value) {
      bitField0_ |= 0x00000004;
      headIndex_ = value;
    }
    /**
     * <pre>
     * The index of the embedder head that produced this embedding. This is useful
     * for multi-head models.
     * </pre>
     *
     * <code>optional int32 head_index = 3;</code>
     */
    private void clearHeadIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      headIndex_ = 0;
    }

    public static final int HEAD_NAME_FIELD_NUMBER = 4;
    private String headName_;
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @return Whether the headName field is set.
     */
    @Override
    public boolean hasHeadName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @return The headName.
     */
    @Override
    public String getHeadName() {
      return headName_;
    }
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @return The bytes for headName.
     */
    @Override
    public com.google.protobuf.ByteString
        getHeadNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(headName_);
    }
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @param value The headName to set.
     */
    private void setHeadName(
        String value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
      headName_ = value;
    }
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     */
    private void clearHeadName() {
      bitField0_ = (bitField0_ & ~0x00000008);
      headName_ = getDefaultInstance().getHeadName();
    }
    /**
     * <pre>
     * The name of the embedder head, which is the corresponding tensor metadata
     * name (if any). This is useful for multi-head models.
     * </pre>
     *
     * <code>optional string head_name = 4;</code>
     * @param value The bytes for headName to set.
     */
    private void setHeadNameBytes(
        com.google.protobuf.ByteString value) {
      headName_ = value.toStringUtf8();
      bitField0_ |= 0x00000008;
    }

    public static Embedding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Embedding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Embedding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Embedding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Embedding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Embedding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Embedding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Embedding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Embedding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Embedding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Embedding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Embedding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Embedding prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Embedding result for a given embedder head.
     * </pre>
     *
     * Protobuf type {@code mediapipe.tasks.components.containers.proto.Embedding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Embedding, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.components.containers.proto.Embedding)
        EmbeddingOrBuilder {
      // Construct using com.google.mediapipe.tasks.components.containers.proto.EmbeddingsProto.Embedding.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public EmbeddingCase
          getEmbeddingCase() {
        return instance.getEmbeddingCase();
      }

      public Builder clearEmbedding() {
        copyOnWrite();
        instance.clearEmbedding();
        return this;
      }


      /**
       * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
       */
      @Override
      public boolean hasFloatEmbedding() {
        return instance.hasFloatEmbedding();
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
       */
      @Override
      public FloatEmbedding getFloatEmbedding() {
        return instance.getFloatEmbedding();
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
       */
      public Builder setFloatEmbedding(FloatEmbedding value) {
        copyOnWrite();
        instance.setFloatEmbedding(value);
        return this;
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
       */
      public Builder setFloatEmbedding(
          FloatEmbedding.Builder builderForValue) {
        copyOnWrite();
        instance.setFloatEmbedding(builderForValue.build());
        return this;
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
       */
      public Builder mergeFloatEmbedding(FloatEmbedding value) {
        copyOnWrite();
        instance.mergeFloatEmbedding(value);
        return this;
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.FloatEmbedding float_embedding = 1;</code>
       */
      public Builder clearFloatEmbedding() {
        copyOnWrite();
        instance.clearFloatEmbedding();
        return this;
      }

      /**
       * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
       */
      @Override
      public boolean hasQuantizedEmbedding() {
        return instance.hasQuantizedEmbedding();
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
       */
      @Override
      public QuantizedEmbedding getQuantizedEmbedding() {
        return instance.getQuantizedEmbedding();
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
       */
      public Builder setQuantizedEmbedding(QuantizedEmbedding value) {
        copyOnWrite();
        instance.setQuantizedEmbedding(value);
        return this;
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
       */
      public Builder setQuantizedEmbedding(
          QuantizedEmbedding.Builder builderForValue) {
        copyOnWrite();
        instance.setQuantizedEmbedding(builderForValue.build());
        return this;
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
       */
      public Builder mergeQuantizedEmbedding(QuantizedEmbedding value) {
        copyOnWrite();
        instance.mergeQuantizedEmbedding(value);
        return this;
      }
      /**
       * <code>.mediapipe.tasks.components.containers.proto.QuantizedEmbedding quantized_embedding = 2;</code>
       */
      public Builder clearQuantizedEmbedding() {
        copyOnWrite();
        instance.clearQuantizedEmbedding();
        return this;
      }

      /**
       * <pre>
       * The index of the embedder head that produced this embedding. This is useful
       * for multi-head models.
       * </pre>
       *
       * <code>optional int32 head_index = 3;</code>
       * @return Whether the headIndex field is set.
       */
      @Override
      public boolean hasHeadIndex() {
        return instance.hasHeadIndex();
      }
      /**
       * <pre>
       * The index of the embedder head that produced this embedding. This is useful
       * for multi-head models.
       * </pre>
       *
       * <code>optional int32 head_index = 3;</code>
       * @return The headIndex.
       */
      @Override
      public int getHeadIndex() {
        return instance.getHeadIndex();
      }
      /**
       * <pre>
       * The index of the embedder head that produced this embedding. This is useful
       * for multi-head models.
       * </pre>
       *
       * <code>optional int32 head_index = 3;</code>
       * @param value The headIndex to set.
       * @return This builder for chaining.
       */
      public Builder setHeadIndex(int value) {
        copyOnWrite();
        instance.setHeadIndex(value);
        return this;
      }
      /**
       * <pre>
       * The index of the embedder head that produced this embedding. This is useful
       * for multi-head models.
       * </pre>
       *
       * <code>optional int32 head_index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadIndex() {
        copyOnWrite();
        instance.clearHeadIndex();
        return this;
      }

      /**
       * <pre>
       * The name of the embedder head, which is the corresponding tensor metadata
       * name (if any). This is useful for multi-head models.
       * </pre>
       *
       * <code>optional string head_name = 4;</code>
       * @return Whether the headName field is set.
       */
      @Override
      public boolean hasHeadName() {
        return instance.hasHeadName();
      }
      /**
       * <pre>
       * The name of the embedder head, which is the corresponding tensor metadata
       * name (if any). This is useful for multi-head models.
       * </pre>
       *
       * <code>optional string head_name = 4;</code>
       * @return The headName.
       */
      @Override
      public String getHeadName() {
        return instance.getHeadName();
      }
      /**
       * <pre>
       * The name of the embedder head, which is the corresponding tensor metadata
       * name (if any). This is useful for multi-head models.
       * </pre>
       *
       * <code>optional string head_name = 4;</code>
       * @return The bytes for headName.
       */
      @Override
      public com.google.protobuf.ByteString
          getHeadNameBytes() {
        return instance.getHeadNameBytes();
      }
      /**
       * <pre>
       * The name of the embedder head, which is the corresponding tensor metadata
       * name (if any). This is useful for multi-head models.
       * </pre>
       *
       * <code>optional string head_name = 4;</code>
       * @param value The headName to set.
       * @return This builder for chaining.
       */
      public Builder setHeadName(
          String value) {
        copyOnWrite();
        instance.setHeadName(value);
        return this;
      }
      /**
       * <pre>
       * The name of the embedder head, which is the corresponding tensor metadata
       * name (if any). This is useful for multi-head models.
       * </pre>
       *
       * <code>optional string head_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadName() {
        copyOnWrite();
        instance.clearHeadName();
        return this;
      }
      /**
       * <pre>
       * The name of the embedder head, which is the corresponding tensor metadata
       * name (if any). This is useful for multi-head models.
       * </pre>
       *
       * <code>optional string head_name = 4;</code>
       * @param value The bytes for headName to set.
       * @return This builder for chaining.
       */
      public Builder setHeadNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHeadNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.components.containers.proto.Embedding)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Embedding();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "embedding_",
              "embeddingCase_",
              "bitField0_",
              FloatEmbedding.class,
              QuantizedEmbedding.class,
              "headIndex_",
              "headName_",
            };
            String info =
                "\u0001\u0004\u0001\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u103c\u0000\u0002" +
                "\u103c\u0000\u0003\u1004\u0002\u0004\u1008\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Embedding> parser = PARSER;
          if (parser == null) {
            synchronized (Embedding.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Embedding>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.components.containers.proto.Embedding)
    private static final Embedding DEFAULT_INSTANCE;
    static {
      Embedding defaultInstance = new Embedding();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Embedding.class, defaultInstance);
    }

    public static Embedding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Embedding> PARSER;

    public static com.google.protobuf.Parser<Embedding> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EmbeddingResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.components.containers.proto.EmbeddingResult)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    java.util.List<Embedding>
        getEmbeddingsList();
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    Embedding getEmbeddings(int index);
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    int getEmbeddingsCount();

    /**
     * <pre>
     * The optional timestamp (in milliseconds) of the start of the chunk of data
     * corresponding to these results.
     * This is only used for embedding extraction on time series (e.g. audio
     * embedding). In these use cases, the amount of data to process might
     * exceed the maximum size that the model can process: to solve this, the
     * input data is split into multiple chunks starting at different timestamps.
     * </pre>
     *
     * <code>optional int64 timestamp_ms = 2;</code>
     * @return Whether the timestampMs field is set.
     */
    boolean hasTimestampMs();
    /**
     * <pre>
     * The optional timestamp (in milliseconds) of the start of the chunk of data
     * corresponding to these results.
     * This is only used for embedding extraction on time series (e.g. audio
     * embedding). In these use cases, the amount of data to process might
     * exceed the maximum size that the model can process: to solve this, the
     * input data is split into multiple chunks starting at different timestamps.
     * </pre>
     *
     * <code>optional int64 timestamp_ms = 2;</code>
     * @return The timestampMs.
     */
    long getTimestampMs();
  }
  /**
   * <pre>
   * Embedding results for a given embedder model.
   * </pre>
   *
   * Protobuf type {@code mediapipe.tasks.components.containers.proto.EmbeddingResult}
   */
  public  static final class EmbeddingResult extends
      com.google.protobuf.GeneratedMessageLite<
          EmbeddingResult, EmbeddingResult.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.components.containers.proto.EmbeddingResult)
      EmbeddingResultOrBuilder {
    private EmbeddingResult() {
      embeddings_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int EMBEDDINGS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Embedding> embeddings_;
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    @Override
    public java.util.List<Embedding> getEmbeddingsList() {
      return embeddings_;
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    public java.util.List<? extends EmbeddingOrBuilder>
        getEmbeddingsOrBuilderList() {
      return embeddings_;
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    @Override
    public int getEmbeddingsCount() {
      return embeddings_.size();
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    @Override
    public Embedding getEmbeddings(int index) {
      return embeddings_.get(index);
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    public EmbeddingOrBuilder getEmbeddingsOrBuilder(
        int index) {
      return embeddings_.get(index);
    }
    private void ensureEmbeddingsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Embedding> tmp = embeddings_;
      if (!tmp.isModifiable()) {
        embeddings_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    private void setEmbeddings(
        int index, Embedding value) {
      value.getClass();
  ensureEmbeddingsIsMutable();
      embeddings_.set(index, value);
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    private void addEmbeddings(Embedding value) {
      value.getClass();
  ensureEmbeddingsIsMutable();
      embeddings_.add(value);
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    private void addEmbeddings(
        int index, Embedding value) {
      value.getClass();
  ensureEmbeddingsIsMutable();
      embeddings_.add(index, value);
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    private void addAllEmbeddings(
        Iterable<? extends Embedding> values) {
      ensureEmbeddingsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, embeddings_);
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    private void clearEmbeddings() {
      embeddings_ = emptyProtobufList();
    }
    /**
     * <pre>
     * The embedding results for each model head, i.e. one for each output tensor.
     * </pre>
     *
     * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
     */
    private void removeEmbeddings(int index) {
      ensureEmbeddingsIsMutable();
      embeddings_.remove(index);
    }

    public static final int TIMESTAMP_MS_FIELD_NUMBER = 2;
    private long timestampMs_;
    /**
     * <pre>
     * The optional timestamp (in milliseconds) of the start of the chunk of data
     * corresponding to these results.
     * This is only used for embedding extraction on time series (e.g. audio
     * embedding). In these use cases, the amount of data to process might
     * exceed the maximum size that the model can process: to solve this, the
     * input data is split into multiple chunks starting at different timestamps.
     * </pre>
     *
     * <code>optional int64 timestamp_ms = 2;</code>
     * @return Whether the timestampMs field is set.
     */
    @Override
    public boolean hasTimestampMs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The optional timestamp (in milliseconds) of the start of the chunk of data
     * corresponding to these results.
     * This is only used for embedding extraction on time series (e.g. audio
     * embedding). In these use cases, the amount of data to process might
     * exceed the maximum size that the model can process: to solve this, the
     * input data is split into multiple chunks starting at different timestamps.
     * </pre>
     *
     * <code>optional int64 timestamp_ms = 2;</code>
     * @return The timestampMs.
     */
    @Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <pre>
     * The optional timestamp (in milliseconds) of the start of the chunk of data
     * corresponding to these results.
     * This is only used for embedding extraction on time series (e.g. audio
     * embedding). In these use cases, the amount of data to process might
     * exceed the maximum size that the model can process: to solve this, the
     * input data is split into multiple chunks starting at different timestamps.
     * </pre>
     *
     * <code>optional int64 timestamp_ms = 2;</code>
     * @param value The timestampMs to set.
     */
    private void setTimestampMs(long value) {
      bitField0_ |= 0x00000001;
      timestampMs_ = value;
    }
    /**
     * <pre>
     * The optional timestamp (in milliseconds) of the start of the chunk of data
     * corresponding to these results.
     * This is only used for embedding extraction on time series (e.g. audio
     * embedding). In these use cases, the amount of data to process might
     * exceed the maximum size that the model can process: to solve this, the
     * input data is split into multiple chunks starting at different timestamps.
     * </pre>
     *
     * <code>optional int64 timestamp_ms = 2;</code>
     */
    private void clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestampMs_ = 0L;
    }

    public static EmbeddingResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmbeddingResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmbeddingResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmbeddingResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmbeddingResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmbeddingResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmbeddingResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmbeddingResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmbeddingResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static EmbeddingResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmbeddingResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmbeddingResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(EmbeddingResult prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Embedding results for a given embedder model.
     * </pre>
     *
     * Protobuf type {@code mediapipe.tasks.components.containers.proto.EmbeddingResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          EmbeddingResult, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.components.containers.proto.EmbeddingResult)
        EmbeddingResultOrBuilder {
      // Construct using com.google.mediapipe.tasks.components.containers.proto.EmbeddingsProto.EmbeddingResult.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      @Override
      public java.util.List<Embedding> getEmbeddingsList() {
        return java.util.Collections.unmodifiableList(
            instance.getEmbeddingsList());
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      @Override
      public int getEmbeddingsCount() {
        return instance.getEmbeddingsCount();
      }/**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      @Override
      public Embedding getEmbeddings(int index) {
        return instance.getEmbeddings(index);
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder setEmbeddings(
          int index, Embedding value) {
        copyOnWrite();
        instance.setEmbeddings(index, value);
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder setEmbeddings(
          int index, Embedding.Builder builderForValue) {
        copyOnWrite();
        instance.setEmbeddings(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder addEmbeddings(Embedding value) {
        copyOnWrite();
        instance.addEmbeddings(value);
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder addEmbeddings(
          int index, Embedding value) {
        copyOnWrite();
        instance.addEmbeddings(index, value);
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder addEmbeddings(
          Embedding.Builder builderForValue) {
        copyOnWrite();
        instance.addEmbeddings(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder addEmbeddings(
          int index, Embedding.Builder builderForValue) {
        copyOnWrite();
        instance.addEmbeddings(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder addAllEmbeddings(
          Iterable<? extends Embedding> values) {
        copyOnWrite();
        instance.addAllEmbeddings(values);
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder clearEmbeddings() {
        copyOnWrite();
        instance.clearEmbeddings();
        return this;
      }
      /**
       * <pre>
       * The embedding results for each model head, i.e. one for each output tensor.
       * </pre>
       *
       * <code>repeated .mediapipe.tasks.components.containers.proto.Embedding embeddings = 1;</code>
       */
      public Builder removeEmbeddings(int index) {
        copyOnWrite();
        instance.removeEmbeddings(index);
        return this;
      }

      /**
       * <pre>
       * The optional timestamp (in milliseconds) of the start of the chunk of data
       * corresponding to these results.
       * This is only used for embedding extraction on time series (e.g. audio
       * embedding). In these use cases, the amount of data to process might
       * exceed the maximum size that the model can process: to solve this, the
       * input data is split into multiple chunks starting at different timestamps.
       * </pre>
       *
       * <code>optional int64 timestamp_ms = 2;</code>
       * @return Whether the timestampMs field is set.
       */
      @Override
      public boolean hasTimestampMs() {
        return instance.hasTimestampMs();
      }
      /**
       * <pre>
       * The optional timestamp (in milliseconds) of the start of the chunk of data
       * corresponding to these results.
       * This is only used for embedding extraction on time series (e.g. audio
       * embedding). In these use cases, the amount of data to process might
       * exceed the maximum size that the model can process: to solve this, the
       * input data is split into multiple chunks starting at different timestamps.
       * </pre>
       *
       * <code>optional int64 timestamp_ms = 2;</code>
       * @return The timestampMs.
       */
      @Override
      public long getTimestampMs() {
        return instance.getTimestampMs();
      }
      /**
       * <pre>
       * The optional timestamp (in milliseconds) of the start of the chunk of data
       * corresponding to these results.
       * This is only used for embedding extraction on time series (e.g. audio
       * embedding). In these use cases, the amount of data to process might
       * exceed the maximum size that the model can process: to solve this, the
       * input data is split into multiple chunks starting at different timestamps.
       * </pre>
       *
       * <code>optional int64 timestamp_ms = 2;</code>
       * @param value The timestampMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampMs(long value) {
        copyOnWrite();
        instance.setTimestampMs(value);
        return this;
      }
      /**
       * <pre>
       * The optional timestamp (in milliseconds) of the start of the chunk of data
       * corresponding to these results.
       * This is only used for embedding extraction on time series (e.g. audio
       * embedding). In these use cases, the amount of data to process might
       * exceed the maximum size that the model can process: to solve this, the
       * input data is split into multiple chunks starting at different timestamps.
       * </pre>
       *
       * <code>optional int64 timestamp_ms = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampMs() {
        copyOnWrite();
        instance.clearTimestampMs();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.components.containers.proto.EmbeddingResult)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new EmbeddingResult();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "embeddings_",
              Embedding.class,
              "timestampMs_",
            };
            String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u1002" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<EmbeddingResult> parser = PARSER;
          if (parser == null) {
            synchronized (EmbeddingResult.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<EmbeddingResult>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.components.containers.proto.EmbeddingResult)
    private static final EmbeddingResult DEFAULT_INSTANCE;
    static {
      EmbeddingResult defaultInstance = new EmbeddingResult();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        EmbeddingResult.class, defaultInstance);
    }

    public static EmbeddingResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EmbeddingResult> PARSER;

    public static com.google.protobuf.Parser<EmbeddingResult> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
