package com.google.mediapipe.tasks.text.textembedder;

import com.google.mediapipe.tasks.core.BaseOptions;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_TextEmbedder_TextEmbedderOptions extends TextEmbedder.TextEmbedderOptions {

  private final BaseOptions baseOptions;

  private final boolean l2Normalize;

  private final boolean quantize;

  private AutoValue_TextEmbedder_TextEmbedderOptions(
      BaseOptions baseOptions,
      boolean l2Normalize,
      boolean quantize) {
    this.baseOptions = baseOptions;
    this.l2Normalize = l2Normalize;
    this.quantize = quantize;
  }

  @Override
  BaseOptions baseOptions() {
    return baseOptions;
  }

  @Override
  boolean l2Normalize() {
    return l2Normalize;
  }

  @Override
  boolean quantize() {
    return quantize;
  }

  @Override
  public String toString() {
    return "TextEmbedderOptions{"
        + "baseOptions=" + baseOptions + ", "
        + "l2Normalize=" + l2Normalize + ", "
        + "quantize=" + quantize
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof TextEmbedder.TextEmbedderOptions) {
      TextEmbedder.TextEmbedderOptions that = (TextEmbedder.TextEmbedderOptions) o;
      return this.baseOptions.equals(that.baseOptions())
          && this.l2Normalize == that.l2Normalize()
          && this.quantize == that.quantize();
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= baseOptions.hashCode();
    h$ *= 1000003;
    h$ ^= l2Normalize ? 1231 : 1237;
    h$ *= 1000003;
    h$ ^= quantize ? 1231 : 1237;
    return h$;
  }

  static final class Builder extends TextEmbedder.TextEmbedderOptions.Builder {
    private BaseOptions baseOptions;
    private Boolean l2Normalize;
    private Boolean quantize;
    Builder() {
    }
    @Override
    public TextEmbedder.TextEmbedderOptions.Builder setBaseOptions(BaseOptions baseOptions) {
      if (baseOptions == null) {
        throw new NullPointerException("Null baseOptions");
      }
      this.baseOptions = baseOptions;
      return this;
    }
    @Override
    public TextEmbedder.TextEmbedderOptions.Builder setL2Normalize(boolean l2Normalize) {
      this.l2Normalize = l2Normalize;
      return this;
    }
    @Override
    public TextEmbedder.TextEmbedderOptions.Builder setQuantize(boolean quantize) {
      this.quantize = quantize;
      return this;
    }
    @Override
    public TextEmbedder.TextEmbedderOptions build() {
      String missing = "";
      if (this.baseOptions == null) {
        missing += " baseOptions";
      }
      if (this.l2Normalize == null) {
        missing += " l2Normalize";
      }
      if (this.quantize == null) {
        missing += " quantize";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_TextEmbedder_TextEmbedderOptions(
          this.baseOptions,
          this.l2Normalize,
          this.quantize);
    }
  }

}
