// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/vision/face_landmarker/proto/face_landmarker_graph_options.proto

package com.google.mediapipe.tasks.vision.facelandmarker.proto;

public final class FaceLandmarkerGraphOptionsProto {
  private FaceLandmarkerGraphOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(FaceLandmarkerGraphOptions.ext);
  }
  public interface FaceLandmarkerGraphOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return Whether the baseOptions field is set.
     */
    boolean hasBaseOptions();
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return The baseOptions.
     */
    com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions();

    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     * @return Whether the faceDetectorGraphOptions field is set.
     */
    boolean hasFaceDetectorGraphOptions();
    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     * @return The faceDetectorGraphOptions.
     */
    com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions getFaceDetectorGraphOptions();

    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     * @return Whether the faceLandmarksDetectorGraphOptions field is set.
     */
    boolean hasFaceLandmarksDetectorGraphOptions();
    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     * @return The faceLandmarksDetectorGraphOptions.
     */
    FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions getFaceLandmarksDetectorGraphOptions();

    /**
     * <pre>
     * Minimum confidence for face landmarks tracking to be considered
     * successfully.
     * </pre>
     *
     * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
     * @return Whether the minTrackingConfidence field is set.
     */
    boolean hasMinTrackingConfidence();
    /**
     * <pre>
     * Minimum confidence for face landmarks tracking to be considered
     * successfully.
     * </pre>
     *
     * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
     * @return The minTrackingConfidence.
     */
    float getMinTrackingConfidence();

    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     * @return Whether the faceGeometryGraphOptions field is set.
     */
    boolean hasFaceGeometryGraphOptions();
    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     * @return The faceGeometryGraphOptions.
     */
    com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions getFaceGeometryGraphOptions();
  }
  /**
   * Protobuf type {@code mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions}
   */
  public  static final class FaceLandmarkerGraphOptions extends
      com.google.protobuf.GeneratedMessageLite<
          FaceLandmarkerGraphOptions, FaceLandmarkerGraphOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions)
      FaceLandmarkerGraphOptionsOrBuilder {
    private FaceLandmarkerGraphOptions() {
      minTrackingConfidence_ = 0.5F;
    }
    private int bitField0_;
    public static final int BASE_OPTIONS_FIELD_NUMBER = 1;
    private com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions baseOptions_;
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public boolean hasBaseOptions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
      return baseOptions_ == null ? com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance() : baseOptions_;
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  baseOptions_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  if (baseOptions_ != null &&
          baseOptions_ != com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance()) {
        baseOptions_ =
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.newBuilder(baseOptions_).mergeFrom(value).buildPartial();
      } else {
        baseOptions_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void clearBaseOptions() {  baseOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int FACE_DETECTOR_GRAPH_OPTIONS_FIELD_NUMBER = 2;
    private com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions faceDetectorGraphOptions_;
    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     */
    @Override
    public boolean hasFaceDetectorGraphOptions() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     */
    @Override
    public com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions getFaceDetectorGraphOptions() {
      return faceDetectorGraphOptions_ == null ? com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions.getDefaultInstance() : faceDetectorGraphOptions_;
    }
    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     */
    private void setFaceDetectorGraphOptions(com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions value) {
      value.getClass();
  faceDetectorGraphOptions_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeFaceDetectorGraphOptions(com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions value) {
      value.getClass();
  if (faceDetectorGraphOptions_ != null &&
          faceDetectorGraphOptions_ != com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions.getDefaultInstance()) {
        faceDetectorGraphOptions_ =
          com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions.newBuilder(faceDetectorGraphOptions_).mergeFrom(value).buildPartial();
      } else {
        faceDetectorGraphOptions_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * Options for face detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
     */
    private void clearFaceDetectorGraphOptions() {  faceDetectorGraphOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int FACE_LANDMARKS_DETECTOR_GRAPH_OPTIONS_FIELD_NUMBER = 3;
    private FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions faceLandmarksDetectorGraphOptions_;
    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     */
    @Override
    public boolean hasFaceLandmarksDetectorGraphOptions() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     */
    @Override
    public FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions getFaceLandmarksDetectorGraphOptions() {
      return faceLandmarksDetectorGraphOptions_ == null ? FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions.getDefaultInstance() : faceLandmarksDetectorGraphOptions_;
    }
    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     */
    private void setFaceLandmarksDetectorGraphOptions(FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions value) {
      value.getClass();
  faceLandmarksDetectorGraphOptions_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeFaceLandmarksDetectorGraphOptions(FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions value) {
      value.getClass();
  if (faceLandmarksDetectorGraphOptions_ != null &&
          faceLandmarksDetectorGraphOptions_ != FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions.getDefaultInstance()) {
        faceLandmarksDetectorGraphOptions_ =
          FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions.newBuilder(faceLandmarksDetectorGraphOptions_).mergeFrom(value).buildPartial();
      } else {
        faceLandmarksDetectorGraphOptions_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * Options for face landmarks detector graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
     */
    private void clearFaceLandmarksDetectorGraphOptions() {  faceLandmarksDetectorGraphOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static final int MIN_TRACKING_CONFIDENCE_FIELD_NUMBER = 4;
    private float minTrackingConfidence_;
    /**
     * <pre>
     * Minimum confidence for face landmarks tracking to be considered
     * successfully.
     * </pre>
     *
     * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
     * @return Whether the minTrackingConfidence field is set.
     */
    @Override
    public boolean hasMinTrackingConfidence() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Minimum confidence for face landmarks tracking to be considered
     * successfully.
     * </pre>
     *
     * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
     * @return The minTrackingConfidence.
     */
    @Override
    public float getMinTrackingConfidence() {
      return minTrackingConfidence_;
    }
    /**
     * <pre>
     * Minimum confidence for face landmarks tracking to be considered
     * successfully.
     * </pre>
     *
     * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
     * @param value The minTrackingConfidence to set.
     */
    private void setMinTrackingConfidence(float value) {
      bitField0_ |= 0x00000008;
      minTrackingConfidence_ = value;
    }
    /**
     * <pre>
     * Minimum confidence for face landmarks tracking to be considered
     * successfully.
     * </pre>
     *
     * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
     */
    private void clearMinTrackingConfidence() {
      bitField0_ = (bitField0_ & ~0x00000008);
      minTrackingConfidence_ = 0.5F;
    }

    public static final int FACE_GEOMETRY_GRAPH_OPTIONS_FIELD_NUMBER = 5;
    private com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions faceGeometryGraphOptions_;
    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     */
    @Override
    public boolean hasFaceGeometryGraphOptions() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     */
    @Override
    public com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions getFaceGeometryGraphOptions() {
      return faceGeometryGraphOptions_ == null ? com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions.getDefaultInstance() : faceGeometryGraphOptions_;
    }
    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     */
    private void setFaceGeometryGraphOptions(com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions value) {
      value.getClass();
  faceGeometryGraphOptions_ = value;
      bitField0_ |= 0x00000010;
      }
    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeFaceGeometryGraphOptions(com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions value) {
      value.getClass();
  if (faceGeometryGraphOptions_ != null &&
          faceGeometryGraphOptions_ != com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions.getDefaultInstance()) {
        faceGeometryGraphOptions_ =
          com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions.newBuilder(faceGeometryGraphOptions_).mergeFrom(value).buildPartial();
      } else {
        faceGeometryGraphOptions_ = value;
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * Options for FaceGeometryGraph to get facial transformation matrix.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
     */
    private void clearFaceGeometryGraphOptions() {  faceGeometryGraphOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000010);
    }

    public static FaceLandmarkerGraphOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceLandmarkerGraphOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceLandmarkerGraphOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FaceLandmarkerGraphOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static FaceLandmarkerGraphOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FaceLandmarkerGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(FaceLandmarkerGraphOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FaceLandmarkerGraphOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions)
        FaceLandmarkerGraphOptionsOrBuilder {
      // Construct using com.google.mediapipe.tasks.vision.facelandmarker.proto.FaceLandmarkerGraphOptionsProto.FaceLandmarkerGraphOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public boolean hasBaseOptions() {
        return instance.hasBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
        return instance.getBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.setBaseOptions(value);
        return this;
        }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setBaseOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.mergeBaseOptions(value);
        return this;
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder clearBaseOptions() {  copyOnWrite();
        instance.clearBaseOptions();
        return this;
      }

      /**
       * <pre>
       * Options for face detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
       */
      @Override
      public boolean hasFaceDetectorGraphOptions() {
        return instance.hasFaceDetectorGraphOptions();
      }
      /**
       * <pre>
       * Options for face detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
       */
      @Override
      public com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions getFaceDetectorGraphOptions() {
        return instance.getFaceDetectorGraphOptions();
      }
      /**
       * <pre>
       * Options for face detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
       */
      public Builder setFaceDetectorGraphOptions(com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions value) {
        copyOnWrite();
        instance.setFaceDetectorGraphOptions(value);
        return this;
        }
      /**
       * <pre>
       * Options for face detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
       */
      public Builder setFaceDetectorGraphOptions(
          com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setFaceDetectorGraphOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Options for face detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
       */
      public Builder mergeFaceDetectorGraphOptions(com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions value) {
        copyOnWrite();
        instance.mergeFaceDetectorGraphOptions(value);
        return this;
      }
      /**
       * <pre>
       * Options for face detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions face_detector_graph_options = 2;</code>
       */
      public Builder clearFaceDetectorGraphOptions() {  copyOnWrite();
        instance.clearFaceDetectorGraphOptions();
        return this;
      }

      /**
       * <pre>
       * Options for face landmarks detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
       */
      @Override
      public boolean hasFaceLandmarksDetectorGraphOptions() {
        return instance.hasFaceLandmarksDetectorGraphOptions();
      }
      /**
       * <pre>
       * Options for face landmarks detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
       */
      @Override
      public FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions getFaceLandmarksDetectorGraphOptions() {
        return instance.getFaceLandmarksDetectorGraphOptions();
      }
      /**
       * <pre>
       * Options for face landmarks detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
       */
      public Builder setFaceLandmarksDetectorGraphOptions(FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions value) {
        copyOnWrite();
        instance.setFaceLandmarksDetectorGraphOptions(value);
        return this;
        }
      /**
       * <pre>
       * Options for face landmarks detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
       */
      public Builder setFaceLandmarksDetectorGraphOptions(
          FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setFaceLandmarksDetectorGraphOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Options for face landmarks detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
       */
      public Builder mergeFaceLandmarksDetectorGraphOptions(FaceLandmarksDetectorGraphOptionsProto.FaceLandmarksDetectorGraphOptions value) {
        copyOnWrite();
        instance.mergeFaceLandmarksDetectorGraphOptions(value);
        return this;
      }
      /**
       * <pre>
       * Options for face landmarks detector graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarksDetectorGraphOptions face_landmarks_detector_graph_options = 3;</code>
       */
      public Builder clearFaceLandmarksDetectorGraphOptions() {  copyOnWrite();
        instance.clearFaceLandmarksDetectorGraphOptions();
        return this;
      }

      /**
       * <pre>
       * Minimum confidence for face landmarks tracking to be considered
       * successfully.
       * </pre>
       *
       * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
       * @return Whether the minTrackingConfidence field is set.
       */
      @Override
      public boolean hasMinTrackingConfidence() {
        return instance.hasMinTrackingConfidence();
      }
      /**
       * <pre>
       * Minimum confidence for face landmarks tracking to be considered
       * successfully.
       * </pre>
       *
       * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
       * @return The minTrackingConfidence.
       */
      @Override
      public float getMinTrackingConfidence() {
        return instance.getMinTrackingConfidence();
      }
      /**
       * <pre>
       * Minimum confidence for face landmarks tracking to be considered
       * successfully.
       * </pre>
       *
       * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
       * @param value The minTrackingConfidence to set.
       * @return This builder for chaining.
       */
      public Builder setMinTrackingConfidence(float value) {
        copyOnWrite();
        instance.setMinTrackingConfidence(value);
        return this;
      }
      /**
       * <pre>
       * Minimum confidence for face landmarks tracking to be considered
       * successfully.
       * </pre>
       *
       * <code>optional float min_tracking_confidence = 4 [default = 0.5];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinTrackingConfidence() {
        copyOnWrite();
        instance.clearMinTrackingConfidence();
        return this;
      }

      /**
       * <pre>
       * Options for FaceGeometryGraph to get facial transformation matrix.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
       */
      @Override
      public boolean hasFaceGeometryGraphOptions() {
        return instance.hasFaceGeometryGraphOptions();
      }
      /**
       * <pre>
       * Options for FaceGeometryGraph to get facial transformation matrix.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
       */
      @Override
      public com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions getFaceGeometryGraphOptions() {
        return instance.getFaceGeometryGraphOptions();
      }
      /**
       * <pre>
       * Options for FaceGeometryGraph to get facial transformation matrix.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
       */
      public Builder setFaceGeometryGraphOptions(com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions value) {
        copyOnWrite();
        instance.setFaceGeometryGraphOptions(value);
        return this;
        }
      /**
       * <pre>
       * Options for FaceGeometryGraph to get facial transformation matrix.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
       */
      public Builder setFaceGeometryGraphOptions(
          com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setFaceGeometryGraphOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Options for FaceGeometryGraph to get facial transformation matrix.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
       */
      public Builder mergeFaceGeometryGraphOptions(com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions value) {
        copyOnWrite();
        instance.mergeFaceGeometryGraphOptions(value);
        return this;
      }
      /**
       * <pre>
       * Options for FaceGeometryGraph to get facial transformation matrix.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions face_geometry_graph_options = 5;</code>
       */
      public Builder clearFaceGeometryGraphOptions() {  copyOnWrite();
        instance.clearFaceGeometryGraphOptions();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new FaceLandmarkerGraphOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "baseOptions_",
              "faceDetectorGraphOptions_",
              "faceLandmarksDetectorGraphOptions_",
              "minTrackingConfidence_",
              "faceGeometryGraphOptions_",
            };
            String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1009\u0001\u0003\u1009\u0002\u0004\u1001\u0003\u0005\u1009\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<FaceLandmarkerGraphOptions> parser = PARSER;
          if (parser == null) {
            synchronized (FaceLandmarkerGraphOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<FaceLandmarkerGraphOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.vision.face_landmarker.proto.FaceLandmarkerGraphOptions)
    private static final FaceLandmarkerGraphOptions DEFAULT_INSTANCE;
    static {
      FaceLandmarkerGraphOptions defaultInstance = new FaceLandmarkerGraphOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FaceLandmarkerGraphOptions.class, defaultInstance);
    }

    public static FaceLandmarkerGraphOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FaceLandmarkerGraphOptions> PARSER;

    public static com.google.protobuf.Parser<FaceLandmarkerGraphOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int EXT_FIELD_NUMBER = 508968150;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        FaceLandmarkerGraphOptions> ext = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions.getDefaultInstance(),
          FaceLandmarkerGraphOptions.getDefaultInstance(),
          FaceLandmarkerGraphOptions.getDefaultInstance(),
          null,
          508968150,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          FaceLandmarkerGraphOptions.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
