// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/vision/hand_detector/proto/hand_detector_graph_options.proto

package com.google.mediapipe.tasks.vision.handdetector.proto;

public final class HandDetectorGraphOptionsProto {
  private HandDetectorGraphOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(HandDetectorGraphOptions.ext);
  }
  public interface HandDetectorGraphOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return Whether the baseOptions field is set.
     */
    boolean hasBaseOptions();
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return The baseOptions.
     */
    com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions();

    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a hand in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return Whether the minDetectionConfidence field is set.
     */
    boolean hasMinDetectionConfidence();
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a hand in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return The minDetectionConfidence.
     */
    float getMinDetectionConfidence();

    /**
     * <pre>
     * The maximum number of hands output by the detector.
     * </pre>
     *
     * <code>optional int32 num_hands = 3;</code>
     * @return Whether the numHands field is set.
     */
    boolean hasNumHands();
    /**
     * <pre>
     * The maximum number of hands output by the detector.
     * </pre>
     *
     * <code>optional int32 num_hands = 3;</code>
     * @return The numHands.
     */
    int getNumHands();
  }
  /**
   * Protobuf type {@code mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions}
   */
  public  static final class HandDetectorGraphOptions extends
      com.google.protobuf.GeneratedMessageLite<
          HandDetectorGraphOptions, HandDetectorGraphOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions)
      HandDetectorGraphOptionsOrBuilder {
    private HandDetectorGraphOptions() {
      minDetectionConfidence_ = 0.5F;
    }
    private int bitField0_;
    public static final int BASE_OPTIONS_FIELD_NUMBER = 1;
    private com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions baseOptions_;
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public boolean hasBaseOptions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
      return baseOptions_ == null ? com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance() : baseOptions_;
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  baseOptions_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  if (baseOptions_ != null &&
          baseOptions_ != com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance()) {
        baseOptions_ =
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.newBuilder(baseOptions_).mergeFrom(value).buildPartial();
      } else {
        baseOptions_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void clearBaseOptions() {  baseOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int MIN_DETECTION_CONFIDENCE_FIELD_NUMBER = 2;
    private float minDetectionConfidence_;
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a hand in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return Whether the minDetectionConfidence field is set.
     */
    @Override
    public boolean hasMinDetectionConfidence() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a hand in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return The minDetectionConfidence.
     */
    @Override
    public float getMinDetectionConfidence() {
      return minDetectionConfidence_;
    }
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a hand in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @param value The minDetectionConfidence to set.
     */
    private void setMinDetectionConfidence(float value) {
      bitField0_ |= 0x00000002;
      minDetectionConfidence_ = value;
    }
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a hand in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     */
    private void clearMinDetectionConfidence() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minDetectionConfidence_ = 0.5F;
    }

    public static final int NUM_HANDS_FIELD_NUMBER = 3;
    private int numHands_;
    /**
     * <pre>
     * The maximum number of hands output by the detector.
     * </pre>
     *
     * <code>optional int32 num_hands = 3;</code>
     * @return Whether the numHands field is set.
     */
    @Override
    public boolean hasNumHands() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The maximum number of hands output by the detector.
     * </pre>
     *
     * <code>optional int32 num_hands = 3;</code>
     * @return The numHands.
     */
    @Override
    public int getNumHands() {
      return numHands_;
    }
    /**
     * <pre>
     * The maximum number of hands output by the detector.
     * </pre>
     *
     * <code>optional int32 num_hands = 3;</code>
     * @param value The numHands to set.
     */
    private void setNumHands(int value) {
      bitField0_ |= 0x00000004;
      numHands_ = value;
    }
    /**
     * <pre>
     * The maximum number of hands output by the detector.
     * </pre>
     *
     * <code>optional int32 num_hands = 3;</code>
     */
    private void clearNumHands() {
      bitField0_ = (bitField0_ & ~0x00000004);
      numHands_ = 0;
    }

    public static HandDetectorGraphOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static HandDetectorGraphOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static HandDetectorGraphOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static HandDetectorGraphOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static HandDetectorGraphOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static HandDetectorGraphOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static HandDetectorGraphOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static HandDetectorGraphOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static HandDetectorGraphOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static HandDetectorGraphOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static HandDetectorGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static HandDetectorGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(HandDetectorGraphOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          HandDetectorGraphOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions)
        HandDetectorGraphOptionsOrBuilder {
      // Construct using com.google.mediapipe.tasks.vision.handdetector.proto.HandDetectorGraphOptionsProto.HandDetectorGraphOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public boolean hasBaseOptions() {
        return instance.hasBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
        return instance.getBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.setBaseOptions(value);
        return this;
        }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setBaseOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.mergeBaseOptions(value);
        return this;
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder clearBaseOptions() {  copyOnWrite();
        instance.clearBaseOptions();
        return this;
      }

      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a hand in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @return Whether the minDetectionConfidence field is set.
       */
      @Override
      public boolean hasMinDetectionConfidence() {
        return instance.hasMinDetectionConfidence();
      }
      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a hand in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @return The minDetectionConfidence.
       */
      @Override
      public float getMinDetectionConfidence() {
        return instance.getMinDetectionConfidence();
      }
      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a hand in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @param value The minDetectionConfidence to set.
       * @return This builder for chaining.
       */
      public Builder setMinDetectionConfidence(float value) {
        copyOnWrite();
        instance.setMinDetectionConfidence(value);
        return this;
      }
      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a hand in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinDetectionConfidence() {
        copyOnWrite();
        instance.clearMinDetectionConfidence();
        return this;
      }

      /**
       * <pre>
       * The maximum number of hands output by the detector.
       * </pre>
       *
       * <code>optional int32 num_hands = 3;</code>
       * @return Whether the numHands field is set.
       */
      @Override
      public boolean hasNumHands() {
        return instance.hasNumHands();
      }
      /**
       * <pre>
       * The maximum number of hands output by the detector.
       * </pre>
       *
       * <code>optional int32 num_hands = 3;</code>
       * @return The numHands.
       */
      @Override
      public int getNumHands() {
        return instance.getNumHands();
      }
      /**
       * <pre>
       * The maximum number of hands output by the detector.
       * </pre>
       *
       * <code>optional int32 num_hands = 3;</code>
       * @param value The numHands to set.
       * @return This builder for chaining.
       */
      public Builder setNumHands(int value) {
        copyOnWrite();
        instance.setNumHands(value);
        return this;
      }
      /**
       * <pre>
       * The maximum number of hands output by the detector.
       * </pre>
       *
       * <code>optional int32 num_hands = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumHands() {
        copyOnWrite();
        instance.clearNumHands();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new HandDetectorGraphOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "baseOptions_",
              "minDetectionConfidence_",
              "numHands_",
            };
            String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1001\u0001\u0003\u1004\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<HandDetectorGraphOptions> parser = PARSER;
          if (parser == null) {
            synchronized (HandDetectorGraphOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<HandDetectorGraphOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.vision.hand_detector.proto.HandDetectorGraphOptions)
    private static final HandDetectorGraphOptions DEFAULT_INSTANCE;
    static {
      HandDetectorGraphOptions defaultInstance = new HandDetectorGraphOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HandDetectorGraphOptions.class, defaultInstance);
    }

    public static HandDetectorGraphOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HandDetectorGraphOptions> PARSER;

    public static com.google.protobuf.Parser<HandDetectorGraphOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int EXT_FIELD_NUMBER = 464864288;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        HandDetectorGraphOptions> ext = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions.getDefaultInstance(),
          HandDetectorGraphOptions.getDefaultInstance(),
          HandDetectorGraphOptions.getDefaultInstance(),
          null,
          464864288,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          HandDetectorGraphOptions.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
