// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/vision/gesture_recognizer/proto/gesture_recognizer_graph_options.proto

package com.google.mediapipe.tasks.vision.gesturerecognizer.proto;

public final class GestureRecognizerGraphOptionsProto {
  private GestureRecognizerGraphOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(GestureRecognizerGraphOptions.ext);
  }
  public interface GestureRecognizerGraphOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return Whether the baseOptions field is set.
     */
    boolean hasBaseOptions();
    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return The baseOptions.
     */
    com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions();

    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     * @return Whether the handLandmarkerGraphOptions field is set.
     */
    boolean hasHandLandmarkerGraphOptions();
    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     * @return The handLandmarkerGraphOptions.
     */
    com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions getHandLandmarkerGraphOptions();

    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     * @return Whether the handGestureRecognizerGraphOptions field is set.
     */
    boolean hasHandGestureRecognizerGraphOptions();
    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     * @return The handGestureRecognizerGraphOptions.
     */
    HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions getHandGestureRecognizerGraphOptions();
  }
  /**
   * Protobuf type {@code mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions}
   */
  public  static final class GestureRecognizerGraphOptions extends
      com.google.protobuf.GeneratedMessageLite<
          GestureRecognizerGraphOptions, GestureRecognizerGraphOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions)
      GestureRecognizerGraphOptionsOrBuilder {
    private GestureRecognizerGraphOptions() {
    }
    private int bitField0_;
    public static final int BASE_OPTIONS_FIELD_NUMBER = 1;
    private com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions baseOptions_;
    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public boolean hasBaseOptions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
      return baseOptions_ == null ? com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance() : baseOptions_;
    }
    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  baseOptions_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  if (baseOptions_ != null &&
          baseOptions_ != com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance()) {
        baseOptions_ =
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.newBuilder(baseOptions_).mergeFrom(value).buildPartial();
      } else {
        baseOptions_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Base options for configuring gesture recognizer graph, such as specifying
     * the TfLite model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void clearBaseOptions() {  baseOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int HAND_LANDMARKER_GRAPH_OPTIONS_FIELD_NUMBER = 2;
    private com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions handLandmarkerGraphOptions_;
    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     */
    @Override
    public boolean hasHandLandmarkerGraphOptions() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     */
    @Override
    public com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions getHandLandmarkerGraphOptions() {
      return handLandmarkerGraphOptions_ == null ? com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions.getDefaultInstance() : handLandmarkerGraphOptions_;
    }
    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     */
    private void setHandLandmarkerGraphOptions(com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions value) {
      value.getClass();
  handLandmarkerGraphOptions_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeHandLandmarkerGraphOptions(com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions value) {
      value.getClass();
  if (handLandmarkerGraphOptions_ != null &&
          handLandmarkerGraphOptions_ != com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions.getDefaultInstance()) {
        handLandmarkerGraphOptions_ =
          com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions.newBuilder(handLandmarkerGraphOptions_).mergeFrom(value).buildPartial();
      } else {
        handLandmarkerGraphOptions_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * Options for configuring hand landmarker graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
     */
    private void clearHandLandmarkerGraphOptions() {  handLandmarkerGraphOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int HAND_GESTURE_RECOGNIZER_GRAPH_OPTIONS_FIELD_NUMBER = 3;
    private HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions handGestureRecognizerGraphOptions_;
    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     */
    @Override
    public boolean hasHandGestureRecognizerGraphOptions() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     */
    @Override
    public HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions getHandGestureRecognizerGraphOptions() {
      return handGestureRecognizerGraphOptions_ == null ? HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions.getDefaultInstance() : handGestureRecognizerGraphOptions_;
    }
    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     */
    private void setHandGestureRecognizerGraphOptions(HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions value) {
      value.getClass();
  handGestureRecognizerGraphOptions_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeHandGestureRecognizerGraphOptions(HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions value) {
      value.getClass();
  if (handGestureRecognizerGraphOptions_ != null &&
          handGestureRecognizerGraphOptions_ != HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions.getDefaultInstance()) {
        handGestureRecognizerGraphOptions_ =
          HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions.newBuilder(handGestureRecognizerGraphOptions_).mergeFrom(value).buildPartial();
      } else {
        handGestureRecognizerGraphOptions_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * Options for configuring hand gesture recognizer graph.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
     */
    private void clearHandGestureRecognizerGraphOptions() {  handGestureRecognizerGraphOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static GestureRecognizerGraphOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static GestureRecognizerGraphOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static GestureRecognizerGraphOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static GestureRecognizerGraphOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static GestureRecognizerGraphOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static GestureRecognizerGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(GestureRecognizerGraphOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          GestureRecognizerGraphOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions)
        GestureRecognizerGraphOptionsOrBuilder {
      // Construct using com.google.mediapipe.tasks.vision.gesturerecognizer.proto.GestureRecognizerGraphOptionsProto.GestureRecognizerGraphOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Base options for configuring gesture recognizer graph, such as specifying
       * the TfLite model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public boolean hasBaseOptions() {
        return instance.hasBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring gesture recognizer graph, such as specifying
       * the TfLite model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
        return instance.getBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring gesture recognizer graph, such as specifying
       * the TfLite model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.setBaseOptions(value);
        return this;
        }
      /**
       * <pre>
       * Base options for configuring gesture recognizer graph, such as specifying
       * the TfLite model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setBaseOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Base options for configuring gesture recognizer graph, such as specifying
       * the TfLite model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.mergeBaseOptions(value);
        return this;
      }
      /**
       * <pre>
       * Base options for configuring gesture recognizer graph, such as specifying
       * the TfLite model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder clearBaseOptions() {  copyOnWrite();
        instance.clearBaseOptions();
        return this;
      }

      /**
       * <pre>
       * Options for configuring hand landmarker graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
       */
      @Override
      public boolean hasHandLandmarkerGraphOptions() {
        return instance.hasHandLandmarkerGraphOptions();
      }
      /**
       * <pre>
       * Options for configuring hand landmarker graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
       */
      @Override
      public com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions getHandLandmarkerGraphOptions() {
        return instance.getHandLandmarkerGraphOptions();
      }
      /**
       * <pre>
       * Options for configuring hand landmarker graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
       */
      public Builder setHandLandmarkerGraphOptions(com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions value) {
        copyOnWrite();
        instance.setHandLandmarkerGraphOptions(value);
        return this;
        }
      /**
       * <pre>
       * Options for configuring hand landmarker graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
       */
      public Builder setHandLandmarkerGraphOptions(
          com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setHandLandmarkerGraphOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Options for configuring hand landmarker graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
       */
      public Builder mergeHandLandmarkerGraphOptions(com.google.mediapipe.tasks.vision.handlandmarker.proto.HandLandmarkerGraphOptionsProto.HandLandmarkerGraphOptions value) {
        copyOnWrite();
        instance.mergeHandLandmarkerGraphOptions(value);
        return this;
      }
      /**
       * <pre>
       * Options for configuring hand landmarker graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions hand_landmarker_graph_options = 2;</code>
       */
      public Builder clearHandLandmarkerGraphOptions() {  copyOnWrite();
        instance.clearHandLandmarkerGraphOptions();
        return this;
      }

      /**
       * <pre>
       * Options for configuring hand gesture recognizer graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
       */
      @Override
      public boolean hasHandGestureRecognizerGraphOptions() {
        return instance.hasHandGestureRecognizerGraphOptions();
      }
      /**
       * <pre>
       * Options for configuring hand gesture recognizer graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
       */
      @Override
      public HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions getHandGestureRecognizerGraphOptions() {
        return instance.getHandGestureRecognizerGraphOptions();
      }
      /**
       * <pre>
       * Options for configuring hand gesture recognizer graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
       */
      public Builder setHandGestureRecognizerGraphOptions(HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions value) {
        copyOnWrite();
        instance.setHandGestureRecognizerGraphOptions(value);
        return this;
        }
      /**
       * <pre>
       * Options for configuring hand gesture recognizer graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
       */
      public Builder setHandGestureRecognizerGraphOptions(
          HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setHandGestureRecognizerGraphOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Options for configuring hand gesture recognizer graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
       */
      public Builder mergeHandGestureRecognizerGraphOptions(HandGestureRecognizerGraphOptionsProto.HandGestureRecognizerGraphOptions value) {
        copyOnWrite();
        instance.mergeHandGestureRecognizerGraphOptions(value);
        return this;
      }
      /**
       * <pre>
       * Options for configuring hand gesture recognizer graph.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.gesture_recognizer.proto.HandGestureRecognizerGraphOptions hand_gesture_recognizer_graph_options = 3;</code>
       */
      public Builder clearHandGestureRecognizerGraphOptions() {  copyOnWrite();
        instance.clearHandGestureRecognizerGraphOptions();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new GestureRecognizerGraphOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "baseOptions_",
              "handLandmarkerGraphOptions_",
              "handGestureRecognizerGraphOptions_",
            };
            String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1009\u0001\u0003\u1009\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<GestureRecognizerGraphOptions> parser = PARSER;
          if (parser == null) {
            synchronized (GestureRecognizerGraphOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<GestureRecognizerGraphOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.vision.gesture_recognizer.proto.GestureRecognizerGraphOptions)
    private static final GestureRecognizerGraphOptions DEFAULT_INSTANCE;
    static {
      GestureRecognizerGraphOptions defaultInstance = new GestureRecognizerGraphOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GestureRecognizerGraphOptions.class, defaultInstance);
    }

    public static GestureRecognizerGraphOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GestureRecognizerGraphOptions> PARSER;

    public static com.google.protobuf.Parser<GestureRecognizerGraphOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int EXT_FIELD_NUMBER = 479097054;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        GestureRecognizerGraphOptions> ext = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions.getDefaultInstance(),
          GestureRecognizerGraphOptions.getDefaultInstance(),
          GestureRecognizerGraphOptions.getDefaultInstance(),
          null,
          479097054,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          GestureRecognizerGraphOptions.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
