// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/calculators/core/flow_limiter_calculator.proto

package com.google.mediapipe.calculator.proto;

public final class FlowLimiterCalculatorProto {
  private FlowLimiterCalculatorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(FlowLimiterCalculatorOptions.ext);
  }
  public interface FlowLimiterCalculatorOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.FlowLimiterCalculatorOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The maximum number of frames released for processing at one time.
     * The default value limits to 1 frame processing at a time.
     * </pre>
     *
     * <code>optional int32 max_in_flight = 1 [default = 1];</code>
     * @return Whether the maxInFlight field is set.
     */
    boolean hasMaxInFlight();
    /**
     * <pre>
     * The maximum number of frames released for processing at one time.
     * The default value limits to 1 frame processing at a time.
     * </pre>
     *
     * <code>optional int32 max_in_flight = 1 [default = 1];</code>
     * @return The maxInFlight.
     */
    int getMaxInFlight();

    /**
     * <pre>
     * The maximum number of frames queued waiting for processing.
     * The default value limits to 0 frames awaiting processing.
     * </pre>
     *
     * <code>optional int32 max_in_queue = 2 [default = 0];</code>
     * @return Whether the maxInQueue field is set.
     */
    boolean hasMaxInQueue();
    /**
     * <pre>
     * The maximum number of frames queued waiting for processing.
     * The default value limits to 0 frames awaiting processing.
     * </pre>
     *
     * <code>optional int32 max_in_queue = 2 [default = 0];</code>
     * @return The maxInQueue.
     */
    int getMaxInQueue();

    /**
     * <pre>
     * The maximum time in microseconds to wait for a frame to finish processing.
     * The default value 0 specifies no timeout.
     * </pre>
     *
     * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
     * @return Whether the inFlightTimeout field is set.
     */
    boolean hasInFlightTimeout();
    /**
     * <pre>
     * The maximum time in microseconds to wait for a frame to finish processing.
     * The default value 0 specifies no timeout.
     * </pre>
     *
     * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
     * @return The inFlightTimeout.
     */
    long getInFlightTimeout();
  }
  /**
   * Protobuf type {@code mediapipe.FlowLimiterCalculatorOptions}
   */
  public  static final class FlowLimiterCalculatorOptions extends
      com.google.protobuf.GeneratedMessageLite<
          FlowLimiterCalculatorOptions, FlowLimiterCalculatorOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.FlowLimiterCalculatorOptions)
      FlowLimiterCalculatorOptionsOrBuilder {
    private FlowLimiterCalculatorOptions() {
      maxInFlight_ = 1;
    }
    private int bitField0_;
    public static final int MAX_IN_FLIGHT_FIELD_NUMBER = 1;
    private int maxInFlight_;
    /**
     * <pre>
     * The maximum number of frames released for processing at one time.
     * The default value limits to 1 frame processing at a time.
     * </pre>
     *
     * <code>optional int32 max_in_flight = 1 [default = 1];</code>
     * @return Whether the maxInFlight field is set.
     */
    @Override
    public boolean hasMaxInFlight() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The maximum number of frames released for processing at one time.
     * The default value limits to 1 frame processing at a time.
     * </pre>
     *
     * <code>optional int32 max_in_flight = 1 [default = 1];</code>
     * @return The maxInFlight.
     */
    @Override
    public int getMaxInFlight() {
      return maxInFlight_;
    }
    /**
     * <pre>
     * The maximum number of frames released for processing at one time.
     * The default value limits to 1 frame processing at a time.
     * </pre>
     *
     * <code>optional int32 max_in_flight = 1 [default = 1];</code>
     * @param value The maxInFlight to set.
     */
    private void setMaxInFlight(int value) {
      bitField0_ |= 0x00000001;
      maxInFlight_ = value;
    }
    /**
     * <pre>
     * The maximum number of frames released for processing at one time.
     * The default value limits to 1 frame processing at a time.
     * </pre>
     *
     * <code>optional int32 max_in_flight = 1 [default = 1];</code>
     */
    private void clearMaxInFlight() {
      bitField0_ = (bitField0_ & ~0x00000001);
      maxInFlight_ = 1;
    }

    public static final int MAX_IN_QUEUE_FIELD_NUMBER = 2;
    private int maxInQueue_;
    /**
     * <pre>
     * The maximum number of frames queued waiting for processing.
     * The default value limits to 0 frames awaiting processing.
     * </pre>
     *
     * <code>optional int32 max_in_queue = 2 [default = 0];</code>
     * @return Whether the maxInQueue field is set.
     */
    @Override
    public boolean hasMaxInQueue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The maximum number of frames queued waiting for processing.
     * The default value limits to 0 frames awaiting processing.
     * </pre>
     *
     * <code>optional int32 max_in_queue = 2 [default = 0];</code>
     * @return The maxInQueue.
     */
    @Override
    public int getMaxInQueue() {
      return maxInQueue_;
    }
    /**
     * <pre>
     * The maximum number of frames queued waiting for processing.
     * The default value limits to 0 frames awaiting processing.
     * </pre>
     *
     * <code>optional int32 max_in_queue = 2 [default = 0];</code>
     * @param value The maxInQueue to set.
     */
    private void setMaxInQueue(int value) {
      bitField0_ |= 0x00000002;
      maxInQueue_ = value;
    }
    /**
     * <pre>
     * The maximum number of frames queued waiting for processing.
     * The default value limits to 0 frames awaiting processing.
     * </pre>
     *
     * <code>optional int32 max_in_queue = 2 [default = 0];</code>
     */
    private void clearMaxInQueue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxInQueue_ = 0;
    }

    public static final int IN_FLIGHT_TIMEOUT_FIELD_NUMBER = 3;
    private long inFlightTimeout_;
    /**
     * <pre>
     * The maximum time in microseconds to wait for a frame to finish processing.
     * The default value 0 specifies no timeout.
     * </pre>
     *
     * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
     * @return Whether the inFlightTimeout field is set.
     */
    @Override
    public boolean hasInFlightTimeout() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The maximum time in microseconds to wait for a frame to finish processing.
     * The default value 0 specifies no timeout.
     * </pre>
     *
     * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
     * @return The inFlightTimeout.
     */
    @Override
    public long getInFlightTimeout() {
      return inFlightTimeout_;
    }
    /**
     * <pre>
     * The maximum time in microseconds to wait for a frame to finish processing.
     * The default value 0 specifies no timeout.
     * </pre>
     *
     * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
     * @param value The inFlightTimeout to set.
     */
    private void setInFlightTimeout(long value) {
      bitField0_ |= 0x00000004;
      inFlightTimeout_ = value;
    }
    /**
     * <pre>
     * The maximum time in microseconds to wait for a frame to finish processing.
     * The default value 0 specifies no timeout.
     * </pre>
     *
     * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
     */
    private void clearInFlightTimeout() {
      bitField0_ = (bitField0_ & ~0x00000004);
      inFlightTimeout_ = 0L;
    }

    public static FlowLimiterCalculatorOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FlowLimiterCalculatorOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FlowLimiterCalculatorOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FlowLimiterCalculatorOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static FlowLimiterCalculatorOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FlowLimiterCalculatorOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(FlowLimiterCalculatorOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mediapipe.FlowLimiterCalculatorOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FlowLimiterCalculatorOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.FlowLimiterCalculatorOptions)
        FlowLimiterCalculatorOptionsOrBuilder {
      // Construct using com.google.mediapipe.calculator.proto.FlowLimiterCalculatorProto.FlowLimiterCalculatorOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The maximum number of frames released for processing at one time.
       * The default value limits to 1 frame processing at a time.
       * </pre>
       *
       * <code>optional int32 max_in_flight = 1 [default = 1];</code>
       * @return Whether the maxInFlight field is set.
       */
      @Override
      public boolean hasMaxInFlight() {
        return instance.hasMaxInFlight();
      }
      /**
       * <pre>
       * The maximum number of frames released for processing at one time.
       * The default value limits to 1 frame processing at a time.
       * </pre>
       *
       * <code>optional int32 max_in_flight = 1 [default = 1];</code>
       * @return The maxInFlight.
       */
      @Override
      public int getMaxInFlight() {
        return instance.getMaxInFlight();
      }
      /**
       * <pre>
       * The maximum number of frames released for processing at one time.
       * The default value limits to 1 frame processing at a time.
       * </pre>
       *
       * <code>optional int32 max_in_flight = 1 [default = 1];</code>
       * @param value The maxInFlight to set.
       * @return This builder for chaining.
       */
      public Builder setMaxInFlight(int value) {
        copyOnWrite();
        instance.setMaxInFlight(value);
        return this;
      }
      /**
       * <pre>
       * The maximum number of frames released for processing at one time.
       * The default value limits to 1 frame processing at a time.
       * </pre>
       *
       * <code>optional int32 max_in_flight = 1 [default = 1];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxInFlight() {
        copyOnWrite();
        instance.clearMaxInFlight();
        return this;
      }

      /**
       * <pre>
       * The maximum number of frames queued waiting for processing.
       * The default value limits to 0 frames awaiting processing.
       * </pre>
       *
       * <code>optional int32 max_in_queue = 2 [default = 0];</code>
       * @return Whether the maxInQueue field is set.
       */
      @Override
      public boolean hasMaxInQueue() {
        return instance.hasMaxInQueue();
      }
      /**
       * <pre>
       * The maximum number of frames queued waiting for processing.
       * The default value limits to 0 frames awaiting processing.
       * </pre>
       *
       * <code>optional int32 max_in_queue = 2 [default = 0];</code>
       * @return The maxInQueue.
       */
      @Override
      public int getMaxInQueue() {
        return instance.getMaxInQueue();
      }
      /**
       * <pre>
       * The maximum number of frames queued waiting for processing.
       * The default value limits to 0 frames awaiting processing.
       * </pre>
       *
       * <code>optional int32 max_in_queue = 2 [default = 0];</code>
       * @param value The maxInQueue to set.
       * @return This builder for chaining.
       */
      public Builder setMaxInQueue(int value) {
        copyOnWrite();
        instance.setMaxInQueue(value);
        return this;
      }
      /**
       * <pre>
       * The maximum number of frames queued waiting for processing.
       * The default value limits to 0 frames awaiting processing.
       * </pre>
       *
       * <code>optional int32 max_in_queue = 2 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxInQueue() {
        copyOnWrite();
        instance.clearMaxInQueue();
        return this;
      }

      /**
       * <pre>
       * The maximum time in microseconds to wait for a frame to finish processing.
       * The default value 0 specifies no timeout.
       * </pre>
       *
       * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
       * @return Whether the inFlightTimeout field is set.
       */
      @Override
      public boolean hasInFlightTimeout() {
        return instance.hasInFlightTimeout();
      }
      /**
       * <pre>
       * The maximum time in microseconds to wait for a frame to finish processing.
       * The default value 0 specifies no timeout.
       * </pre>
       *
       * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
       * @return The inFlightTimeout.
       */
      @Override
      public long getInFlightTimeout() {
        return instance.getInFlightTimeout();
      }
      /**
       * <pre>
       * The maximum time in microseconds to wait for a frame to finish processing.
       * The default value 0 specifies no timeout.
       * </pre>
       *
       * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
       * @param value The inFlightTimeout to set.
       * @return This builder for chaining.
       */
      public Builder setInFlightTimeout(long value) {
        copyOnWrite();
        instance.setInFlightTimeout(value);
        return this;
      }
      /**
       * <pre>
       * The maximum time in microseconds to wait for a frame to finish processing.
       * The default value 0 specifies no timeout.
       * </pre>
       *
       * <code>optional int64 in_flight_timeout = 3 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearInFlightTimeout() {
        copyOnWrite();
        instance.clearInFlightTimeout();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.FlowLimiterCalculatorOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new FlowLimiterCalculatorOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "maxInFlight_",
              "maxInQueue_",
              "inFlightTimeout_",
            };
            String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
                "\u1004\u0001\u0003\u1002\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<FlowLimiterCalculatorOptions> parser = PARSER;
          if (parser == null) {
            synchronized (FlowLimiterCalculatorOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<FlowLimiterCalculatorOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.FlowLimiterCalculatorOptions)
    private static final FlowLimiterCalculatorOptions DEFAULT_INSTANCE;
    static {
      FlowLimiterCalculatorOptions defaultInstance = new FlowLimiterCalculatorOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FlowLimiterCalculatorOptions.class, defaultInstance);
    }

    public static FlowLimiterCalculatorOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FlowLimiterCalculatorOptions> PARSER;

    public static com.google.protobuf.Parser<FlowLimiterCalculatorOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int EXT_FIELD_NUMBER = 326963320;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        FlowLimiterCalculatorOptions> ext = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions.getDefaultInstance(),
          FlowLimiterCalculatorOptions.getDefaultInstance(),
          FlowLimiterCalculatorOptions.getDefaultInstance(),
          null,
          326963320,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          FlowLimiterCalculatorOptions.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
