package com.google.mediapipe.tasks.components.containers;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_Connection extends Connection {

  private final int start;

  private final int end;

  AutoValue_Connection(
      int start,
      int end) {
    this.start = start;
    this.end = end;
  }

  @Override
  public int start() {
    return start;
  }

  @Override
  public int end() {
    return end;
  }

  @Override
  public String toString() {
    return "Connection{"
        + "start=" + start + ", "
        + "end=" + end
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Connection) {
      Connection that = (Connection) o;
      return this.start == that.start()
          && this.end == that.end();
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= start;
    h$ *= 1000003;
    h$ ^= end;
    return h$;
  }

}
