package com.google.mediapipe.tasks.components.containers;

import java.util.Optional;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_NormalizedKeypoint extends NormalizedKeypoint {

  private final float x;

  private final float y;

  private final Optional<String> label;

  private final Optional<Float> score;

  AutoValue_NormalizedKeypoint(
      float x,
      float y,
      Optional<String> label,
      Optional<Float> score) {
    this.x = x;
    this.y = y;
    if (label == null) {
      throw new NullPointerException("Null label");
    }
    this.label = label;
    if (score == null) {
      throw new NullPointerException("Null score");
    }
    this.score = score;
  }

  @Override
  public float x() {
    return x;
  }

  @Override
  public float y() {
    return y;
  }

  @Override
  public Optional<String> label() {
    return label;
  }

  @Override
  public Optional<Float> score() {
    return score;
  }

}
