package com.google.mediapipe.tasks.components.containers;

import java.util.Arrays;
import java.util.Optional;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_Embedding extends Embedding {

  private final float[] floatEmbedding;

  private final byte[] quantizedEmbedding;

  private final int headIndex;

  private final Optional<String> headName;

  AutoValue_Embedding(
      float[] floatEmbedding,
      byte[] quantizedEmbedding,
      int headIndex,
      Optional<String> headName) {
    if (floatEmbedding == null) {
      throw new NullPointerException("Null floatEmbedding");
    }
    this.floatEmbedding = floatEmbedding;
    if (quantizedEmbedding == null) {
      throw new NullPointerException("Null quantizedEmbedding");
    }
    this.quantizedEmbedding = quantizedEmbedding;
    this.headIndex = headIndex;
    if (headName == null) {
      throw new NullPointerException("Null headName");
    }
    this.headName = headName;
  }

  @Override
  public float[] floatEmbedding() {
    return floatEmbedding;
  }

  @Override
  public byte[] quantizedEmbedding() {
    return quantizedEmbedding;
  }

  @Override
  public int headIndex() {
    return headIndex;
  }

  @Override
  public Optional<String> headName() {
    return headName;
  }

  @Override
  public String toString() {
    return "Embedding{"
        + "floatEmbedding=" + Arrays.toString(floatEmbedding) + ", "
        + "quantizedEmbedding=" + Arrays.toString(quantizedEmbedding) + ", "
        + "headIndex=" + headIndex + ", "
        + "headName=" + headName
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Embedding) {
      Embedding that = (Embedding) o;
      return Arrays.equals(this.floatEmbedding, (that instanceof AutoValue_Embedding) ? ((AutoValue_Embedding) that).floatEmbedding : that.floatEmbedding())
          && Arrays.equals(this.quantizedEmbedding, (that instanceof AutoValue_Embedding) ? ((AutoValue_Embedding) that).quantizedEmbedding : that.quantizedEmbedding())
          && this.headIndex == that.headIndex()
          && this.headName.equals(that.headName());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= Arrays.hashCode(floatEmbedding);
    h$ *= 1000003;
    h$ ^= Arrays.hashCode(quantizedEmbedding);
    h$ *= 1000003;
    h$ ^= headIndex;
    h$ *= 1000003;
    h$ ^= headName.hashCode();
    return h$;
  }

}
