package com.google.mediapipe.tasks.components.containers;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_Category extends Category {

  private final float score;

  private final int index;

  private final String categoryName;

  private final String displayName;

  AutoValue_Category(
      float score,
      int index,
      String categoryName,
      String displayName) {
    this.score = score;
    this.index = index;
    if (categoryName == null) {
      throw new NullPointerException("Null categoryName");
    }
    this.categoryName = categoryName;
    if (displayName == null) {
      throw new NullPointerException("Null displayName");
    }
    this.displayName = displayName;
  }

  @Override
  public float score() {
    return score;
  }

  @Override
  public int index() {
    return index;
  }

  @Override
  public String categoryName() {
    return categoryName;
  }

  @Override
  public String displayName() {
    return displayName;
  }

}
