package com.google.mediapipe.tasks.audio.audioclassifier;

import com.google.mediapipe.tasks.components.containers.ClassificationResult;

import java.util.List;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_AudioClassifierResult extends AudioClassifierResult {

  private final List<ClassificationResult> classificationResults;

  private final long timestampMs;

  AutoValue_AudioClassifierResult(
      List<ClassificationResult> classificationResults,
      long timestampMs) {
    if (classificationResults == null) {
      throw new NullPointerException("Null classificationResults");
    }
    this.classificationResults = classificationResults;
    this.timestampMs = timestampMs;
  }

  @Override
  public List<ClassificationResult> classificationResults() {
    return classificationResults;
  }

  @Override
  public long timestampMs() {
    return timestampMs;
  }

  @Override
  public String toString() {
    return "AudioClassifierResult{"
        + "classificationResults=" + classificationResults + ", "
        + "timestampMs=" + timestampMs
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof AudioClassifierResult) {
      AudioClassifierResult that = (AudioClassifierResult) o;
      return this.classificationResults.equals(that.classificationResults())
          && this.timestampMs == that.timestampMs();
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= classificationResults.hashCode();
    h$ *= 1000003;
    h$ ^= (int) ((timestampMs >>> 32) ^ timestampMs);
    return h$;
  }

}
