// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/vision/face_detector/proto/face_detector_graph_options.proto

package com.google.mediapipe.tasks.vision.facedetector.proto;

public final class FaceDetectorGraphOptionsProto {
  private FaceDetectorGraphOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(FaceDetectorGraphOptions.ext);
  }
  public interface FaceDetectorGraphOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return Whether the baseOptions field is set.
     */
    boolean hasBaseOptions();
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     * @return The baseOptions.
     */
    com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions();

    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a face in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return Whether the minDetectionConfidence field is set.
     */
    boolean hasMinDetectionConfidence();
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a face in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return The minDetectionConfidence.
     */
    float getMinDetectionConfidence();

    /**
     * <pre>
     * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
     * duplicate detetions.
     * </pre>
     *
     * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
     * @return Whether the minSuppressionThreshold field is set.
     */
    boolean hasMinSuppressionThreshold();
    /**
     * <pre>
     * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
     * duplicate detetions.
     * </pre>
     *
     * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
     * @return The minSuppressionThreshold.
     */
    float getMinSuppressionThreshold();

    /**
     * <pre>
     * Maximum number of faces to detect in the image.
     * </pre>
     *
     * <code>optional int32 num_faces = 4;</code>
     * @return Whether the numFaces field is set.
     */
    boolean hasNumFaces();
    /**
     * <pre>
     * Maximum number of faces to detect in the image.
     * </pre>
     *
     * <code>optional int32 num_faces = 4;</code>
     * @return The numFaces.
     */
    int getNumFaces();
  }
  /**
   * Protobuf type {@code mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions}
   */
  public  static final class FaceDetectorGraphOptions extends
      com.google.protobuf.GeneratedMessageLite<
          FaceDetectorGraphOptions, FaceDetectorGraphOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions)
      FaceDetectorGraphOptionsOrBuilder {
    private FaceDetectorGraphOptions() {
      minDetectionConfidence_ = 0.5F;
      minSuppressionThreshold_ = 0.5F;
    }
    private int bitField0_;
    public static final int BASE_OPTIONS_FIELD_NUMBER = 1;
    private com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions baseOptions_;
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public boolean hasBaseOptions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @Override
    public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
      return baseOptions_ == null ? com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance() : baseOptions_;
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  baseOptions_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
      value.getClass();
  if (baseOptions_ != null &&
          baseOptions_ != com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.getDefaultInstance()) {
        baseOptions_ =
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.newBuilder(baseOptions_).mergeFrom(value).buildPartial();
      } else {
        baseOptions_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Base options for configuring Task library, such as specifying the TfLite
     * model file with metadata, accelerator options, etc.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
     */
    private void clearBaseOptions() {  baseOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int MIN_DETECTION_CONFIDENCE_FIELD_NUMBER = 2;
    private float minDetectionConfidence_;
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a face in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return Whether the minDetectionConfidence field is set.
     */
    @Override
    public boolean hasMinDetectionConfidence() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a face in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @return The minDetectionConfidence.
     */
    @Override
    public float getMinDetectionConfidence() {
      return minDetectionConfidence_;
    }
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a face in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     * @param value The minDetectionConfidence to set.
     */
    private void setMinDetectionConfidence(float value) {
      bitField0_ |= 0x00000002;
      minDetectionConfidence_ = value;
    }
    /**
     * <pre>
     * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
     * successfully detecting a face in the image.
     * </pre>
     *
     * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
     */
    private void clearMinDetectionConfidence() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minDetectionConfidence_ = 0.5F;
    }

    public static final int MIN_SUPPRESSION_THRESHOLD_FIELD_NUMBER = 3;
    private float minSuppressionThreshold_;
    /**
     * <pre>
     * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
     * duplicate detetions.
     * </pre>
     *
     * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
     * @return Whether the minSuppressionThreshold field is set.
     */
    @Override
    public boolean hasMinSuppressionThreshold() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
     * duplicate detetions.
     * </pre>
     *
     * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
     * @return The minSuppressionThreshold.
     */
    @Override
    public float getMinSuppressionThreshold() {
      return minSuppressionThreshold_;
    }
    /**
     * <pre>
     * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
     * duplicate detetions.
     * </pre>
     *
     * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
     * @param value The minSuppressionThreshold to set.
     */
    private void setMinSuppressionThreshold(float value) {
      bitField0_ |= 0x00000004;
      minSuppressionThreshold_ = value;
    }
    /**
     * <pre>
     * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
     * duplicate detetions.
     * </pre>
     *
     * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
     */
    private void clearMinSuppressionThreshold() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minSuppressionThreshold_ = 0.5F;
    }

    public static final int NUM_FACES_FIELD_NUMBER = 4;
    private int numFaces_;
    /**
     * <pre>
     * Maximum number of faces to detect in the image.
     * </pre>
     *
     * <code>optional int32 num_faces = 4;</code>
     * @return Whether the numFaces field is set.
     */
    @Override
    public boolean hasNumFaces() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Maximum number of faces to detect in the image.
     * </pre>
     *
     * <code>optional int32 num_faces = 4;</code>
     * @return The numFaces.
     */
    @Override
    public int getNumFaces() {
      return numFaces_;
    }
    /**
     * <pre>
     * Maximum number of faces to detect in the image.
     * </pre>
     *
     * <code>optional int32 num_faces = 4;</code>
     * @param value The numFaces to set.
     */
    private void setNumFaces(int value) {
      bitField0_ |= 0x00000008;
      numFaces_ = value;
    }
    /**
     * <pre>
     * Maximum number of faces to detect in the image.
     * </pre>
     *
     * <code>optional int32 num_faces = 4;</code>
     */
    private void clearNumFaces() {
      bitField0_ = (bitField0_ & ~0x00000008);
      numFaces_ = 0;
    }

    public static FaceDetectorGraphOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceDetectorGraphOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceDetectorGraphOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceDetectorGraphOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceDetectorGraphOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceDetectorGraphOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceDetectorGraphOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FaceDetectorGraphOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FaceDetectorGraphOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static FaceDetectorGraphOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FaceDetectorGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FaceDetectorGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(FaceDetectorGraphOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FaceDetectorGraphOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions)
        FaceDetectorGraphOptionsOrBuilder {
      // Construct using com.google.mediapipe.tasks.vision.facedetector.proto.FaceDetectorGraphOptionsProto.FaceDetectorGraphOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public boolean hasBaseOptions() {
        return instance.hasBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      @Override
      public com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions getBaseOptions() {
        return instance.getBaseOptions();
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.setBaseOptions(value);
        return this;
        }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder setBaseOptions(
          com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setBaseOptions(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder mergeBaseOptions(com.google.mediapipe.tasks.core.proto.BaseOptionsProto.BaseOptions value) {
        copyOnWrite();
        instance.mergeBaseOptions(value);
        return this;
      }
      /**
       * <pre>
       * Base options for configuring Task library, such as specifying the TfLite
       * model file with metadata, accelerator options, etc.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.core.proto.BaseOptions base_options = 1;</code>
       */
      public Builder clearBaseOptions() {  copyOnWrite();
        instance.clearBaseOptions();
        return this;
      }

      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a face in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @return Whether the minDetectionConfidence field is set.
       */
      @Override
      public boolean hasMinDetectionConfidence() {
        return instance.hasMinDetectionConfidence();
      }
      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a face in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @return The minDetectionConfidence.
       */
      @Override
      public float getMinDetectionConfidence() {
        return instance.getMinDetectionConfidence();
      }
      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a face in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @param value The minDetectionConfidence to set.
       * @return This builder for chaining.
       */
      public Builder setMinDetectionConfidence(float value) {
        copyOnWrite();
        instance.setMinDetectionConfidence(value);
        return this;
      }
      /**
       * <pre>
       * Minimum confidence value ([0.0, 1.0]) for confidence score to be considered
       * successfully detecting a face in the image.
       * </pre>
       *
       * <code>optional float min_detection_confidence = 2 [default = 0.5];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinDetectionConfidence() {
        copyOnWrite();
        instance.clearMinDetectionConfidence();
        return this;
      }

      /**
       * <pre>
       * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
       * duplicate detetions.
       * </pre>
       *
       * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
       * @return Whether the minSuppressionThreshold field is set.
       */
      @Override
      public boolean hasMinSuppressionThreshold() {
        return instance.hasMinSuppressionThreshold();
      }
      /**
       * <pre>
       * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
       * duplicate detetions.
       * </pre>
       *
       * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
       * @return The minSuppressionThreshold.
       */
      @Override
      public float getMinSuppressionThreshold() {
        return instance.getMinSuppressionThreshold();
      }
      /**
       * <pre>
       * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
       * duplicate detetions.
       * </pre>
       *
       * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
       * @param value The minSuppressionThreshold to set.
       * @return This builder for chaining.
       */
      public Builder setMinSuppressionThreshold(float value) {
        copyOnWrite();
        instance.setMinSuppressionThreshold(value);
        return this;
      }
      /**
       * <pre>
       * IoU threshold ([0,0, 1.0]) for non-maximu-suppression to be considered
       * duplicate detetions.
       * </pre>
       *
       * <code>optional float min_suppression_threshold = 3 [default = 0.5];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinSuppressionThreshold() {
        copyOnWrite();
        instance.clearMinSuppressionThreshold();
        return this;
      }

      /**
       * <pre>
       * Maximum number of faces to detect in the image.
       * </pre>
       *
       * <code>optional int32 num_faces = 4;</code>
       * @return Whether the numFaces field is set.
       */
      @Override
      public boolean hasNumFaces() {
        return instance.hasNumFaces();
      }
      /**
       * <pre>
       * Maximum number of faces to detect in the image.
       * </pre>
       *
       * <code>optional int32 num_faces = 4;</code>
       * @return The numFaces.
       */
      @Override
      public int getNumFaces() {
        return instance.getNumFaces();
      }
      /**
       * <pre>
       * Maximum number of faces to detect in the image.
       * </pre>
       *
       * <code>optional int32 num_faces = 4;</code>
       * @param value The numFaces to set.
       * @return This builder for chaining.
       */
      public Builder setNumFaces(int value) {
        copyOnWrite();
        instance.setNumFaces(value);
        return this;
      }
      /**
       * <pre>
       * Maximum number of faces to detect in the image.
       * </pre>
       *
       * <code>optional int32 num_faces = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumFaces() {
        copyOnWrite();
        instance.clearNumFaces();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new FaceDetectorGraphOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "baseOptions_",
              "minDetectionConfidence_",
              "minSuppressionThreshold_",
              "numFaces_",
            };
            String info =
                "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1001\u0001\u0003\u1001\u0002\u0004\u1004\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<FaceDetectorGraphOptions> parser = PARSER;
          if (parser == null) {
            synchronized (FaceDetectorGraphOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<FaceDetectorGraphOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.vision.face_detector.proto.FaceDetectorGraphOptions)
    private static final FaceDetectorGraphOptions DEFAULT_INSTANCE;
    static {
      FaceDetectorGraphOptions defaultInstance = new FaceDetectorGraphOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FaceDetectorGraphOptions.class, defaultInstance);
    }

    public static FaceDetectorGraphOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FaceDetectorGraphOptions> PARSER;

    public static com.google.protobuf.Parser<FaceDetectorGraphOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int EXT_FIELD_NUMBER = 502141897;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        FaceDetectorGraphOptions> ext = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions.getDefaultInstance(),
          FaceDetectorGraphOptions.getDefaultInstance(),
          FaceDetectorGraphOptions.getDefaultInstance(),
          null,
          502141897,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          FaceDetectorGraphOptions.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
