// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/vision/face_geometry/proto/face_geometry_graph_options.proto

package com.google.mediapipe.tasks.vision.facegeometry.proto;

public final class FaceGeometryGraphOptionsProto {
  private FaceGeometryGraphOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(FaceGeometryGraphOptions.ext);
  }
  public interface FaceGeometryGraphOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     * @return Whether the geometryPipelineOptions field is set.
     */
    boolean hasGeometryPipelineOptions();
    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     * @return The geometryPipelineOptions.
     */
    com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions getGeometryPipelineOptions();
  }
  /**
   * Protobuf type {@code mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions}
   */
  public  static final class FaceGeometryGraphOptions extends
      com.google.protobuf.GeneratedMessageLite<
          FaceGeometryGraphOptions, FaceGeometryGraphOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions)
      FaceGeometryGraphOptionsOrBuilder {
    private FaceGeometryGraphOptions() {
    }
    private int bitField0_;
    public static final int GEOMETRY_PIPELINE_OPTIONS_FIELD_NUMBER = 1;
    private com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions geometryPipelineOptions_;
    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     */
    @Override
    public boolean hasGeometryPipelineOptions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     */
    @Override
    public com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions getGeometryPipelineOptions() {
      return geometryPipelineOptions_ == null ? com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions.getDefaultInstance() : geometryPipelineOptions_;
    }
    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     */
    private void setGeometryPipelineOptions(com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions value) {
      value.getClass();
  geometryPipelineOptions_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeGeometryPipelineOptions(com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions value) {
      value.getClass();
  if (geometryPipelineOptions_ != null &&
          geometryPipelineOptions_ != com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions.getDefaultInstance()) {
        geometryPipelineOptions_ =
          com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions.newBuilder(geometryPipelineOptions_).mergeFrom(value).buildPartial();
      } else {
        geometryPipelineOptions_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
     */
    private void clearGeometryPipelineOptions() {  geometryPipelineOptions_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static FaceGeometryGraphOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceGeometryGraphOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceGeometryGraphOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceGeometryGraphOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceGeometryGraphOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FaceGeometryGraphOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FaceGeometryGraphOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FaceGeometryGraphOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FaceGeometryGraphOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static FaceGeometryGraphOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FaceGeometryGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FaceGeometryGraphOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(FaceGeometryGraphOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FaceGeometryGraphOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions)
        FaceGeometryGraphOptionsOrBuilder {
      // Construct using com.google.mediapipe.tasks.vision.facegeometry.proto.FaceGeometryGraphOptionsProto.FaceGeometryGraphOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
       */
      @Override
      public boolean hasGeometryPipelineOptions() {
        return instance.hasGeometryPipelineOptions();
      }
      /**
       * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
       */
      @Override
      public com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions getGeometryPipelineOptions() {
        return instance.getGeometryPipelineOptions();
      }
      /**
       * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
       */
      public Builder setGeometryPipelineOptions(com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions value) {
        copyOnWrite();
        instance.setGeometryPipelineOptions(value);
        return this;
        }
      /**
       * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
       */
      public Builder setGeometryPipelineOptions(
          com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions.Builder builderForValue) {
        copyOnWrite();
        instance.setGeometryPipelineOptions(builderForValue.build());
        return this;
      }
      /**
       * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
       */
      public Builder mergeGeometryPipelineOptions(com.google.mediapipe.tasks.vision.facegeometry.calculators.proto.FaceGeometryPipelineCalculatorOptionsProto.FaceGeometryPipelineCalculatorOptions value) {
        copyOnWrite();
        instance.mergeGeometryPipelineOptions(value);
        return this;
      }
      /**
       * <code>optional .mediapipe.tasks.vision.face_geometry.FaceGeometryPipelineCalculatorOptions geometry_pipeline_options = 1;</code>
       */
      public Builder clearGeometryPipelineOptions() {  copyOnWrite();
        instance.clearGeometryPipelineOptions();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new FaceGeometryGraphOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "geometryPipelineOptions_",
            };
            String info =
                "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<FaceGeometryGraphOptions> parser = PARSER;
          if (parser == null) {
            synchronized (FaceGeometryGraphOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<FaceGeometryGraphOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.vision.face_geometry.proto.FaceGeometryGraphOptions)
    private static final FaceGeometryGraphOptions DEFAULT_INSTANCE;
    static {
      FaceGeometryGraphOptions defaultInstance = new FaceGeometryGraphOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FaceGeometryGraphOptions.class, defaultInstance);
    }

    public static FaceGeometryGraphOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FaceGeometryGraphOptions> PARSER;

    public static com.google.protobuf.Parser<FaceGeometryGraphOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int EXT_FIELD_NUMBER = 515723506;
    /**
     * <code>extend .mediapipe.CalculatorOptions { ... }</code>
     */
    public static final
      GeneratedExtension<
        com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions,
        FaceGeometryGraphOptions> ext = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.mediapipe.proto.CalculatorOptionsProto.CalculatorOptions.getDefaultInstance(),
          FaceGeometryGraphOptions.getDefaultInstance(),
          FaceGeometryGraphOptions.getDefaultInstance(),
          null,
          515723506,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          FaceGeometryGraphOptions.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
