#!/bin/bash
# Copy the OpenCV prebuilt out of Bazel's cache.
#
# OpenCV is the one dependency Bazel links as -lopencv_java4 rather than compiling
# (it contributes none of the 2378 objects). Every other external repo used to be
# vendored here too, but they have all been migrated to git clones under MODULE_REPOS,
# so only these SDK-generated files still need copying.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$ROOT/mediapipesource"
DEST="$ROOT/mediapipe_tasks/src/main/cpp/third_party"
ABI=arm64-v8a

OUTPUT_BASE="$(cd "$SRC" && bazel info output_base)"
EXT="$OUTPUT_BASE/external"
[ -d "$EXT" ] || { echo "no external dir at $EXT" >&2; exit 1; }

echo ">>> opencv prebuilt"
# Bazel links this rather than building OpenCV. The headers come from the checkout under
# opencv/ at the matching tag (cmake/opencv_include_tree.cmake merges them into the flat
# layout), so only these two are needed here: both are generated by OpenCV's CMake and
# describe how this particular SDK build was configured, which no source tree can tell you.
mkdir -p "$DEST/opencv/include/opencv2"
for h in cvconfig.h opencv_modules.hpp; do
  cp "$EXT/android_opencv/sdk/native/jni/include/opencv2/$h" \
     "$DEST/opencv/include/opencv2/$h"
done
mkdir -p "$ROOT/mediapipe_tasks/libs/$ABI"
cp "$EXT/android_opencv/sdk/native/libs/$ABI/libopencv_java4.so" \
   "$ROOT/mediapipe_tasks/libs/$ABI/"

echo ">>> $(du -sh "$DEST" | cut -f1) in $DEST"
