package com.google.mediapipe.tasks.audio.audioembedder;

import com.google.mediapipe.tasks.audio.core.RunningMode;
import com.google.mediapipe.tasks.core.BaseOptions;
import com.google.mediapipe.tasks.core.ErrorListener;
import com.google.mediapipe.tasks.core.OutputHandler;

import java.util.Optional;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_AudioEmbedder_AudioEmbedderOptions extends AudioEmbedder.AudioEmbedderOptions {

  private final BaseOptions baseOptions;

  private final RunningMode runningMode;

  private final boolean l2Normalize;

  private final boolean quantize;

  private final Optional<OutputHandler.PureResultListener<AudioEmbedderResult>> resultListener;

  private final Optional<ErrorListener> errorListener;

  private AutoValue_AudioEmbedder_AudioEmbedderOptions(
      BaseOptions baseOptions,
      RunningMode runningMode,
      boolean l2Normalize,
      boolean quantize,
      Optional<OutputHandler.PureResultListener<AudioEmbedderResult>> resultListener,
      Optional<ErrorListener> errorListener) {
    this.baseOptions = baseOptions;
    this.runningMode = runningMode;
    this.l2Normalize = l2Normalize;
    this.quantize = quantize;
    this.resultListener = resultListener;
    this.errorListener = errorListener;
  }

  @Override
  BaseOptions baseOptions() {
    return baseOptions;
  }

  @Override
  RunningMode runningMode() {
    return runningMode;
  }

  @Override
  boolean l2Normalize() {
    return l2Normalize;
  }

  @Override
  boolean quantize() {
    return quantize;
  }

  @Override
  Optional<OutputHandler.PureResultListener<AudioEmbedderResult>> resultListener() {
    return resultListener;
  }

  @Override
  Optional<ErrorListener> errorListener() {
    return errorListener;
  }

  @Override
  public String toString() {
    return "AudioEmbedderOptions{"
        + "baseOptions=" + baseOptions + ", "
        + "runningMode=" + runningMode + ", "
        + "l2Normalize=" + l2Normalize + ", "
        + "quantize=" + quantize + ", "
        + "resultListener=" + resultListener + ", "
        + "errorListener=" + errorListener
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof AudioEmbedder.AudioEmbedderOptions) {
      AudioEmbedder.AudioEmbedderOptions that = (AudioEmbedder.AudioEmbedderOptions) o;
      return this.baseOptions.equals(that.baseOptions())
          && this.runningMode.equals(that.runningMode())
          && this.l2Normalize == that.l2Normalize()
          && this.quantize == that.quantize()
          && this.resultListener.equals(that.resultListener())
          && this.errorListener.equals(that.errorListener());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= baseOptions.hashCode();
    h$ *= 1000003;
    h$ ^= runningMode.hashCode();
    h$ *= 1000003;
    h$ ^= l2Normalize ? 1231 : 1237;
    h$ *= 1000003;
    h$ ^= quantize ? 1231 : 1237;
    h$ *= 1000003;
    h$ ^= resultListener.hashCode();
    h$ *= 1000003;
    h$ ^= errorListener.hashCode();
    return h$;
  }

  static final class Builder extends AudioEmbedder.AudioEmbedderOptions.Builder {
    private BaseOptions baseOptions;
    private RunningMode runningMode;
    private Boolean l2Normalize;
    private Boolean quantize;
    private Optional<OutputHandler.PureResultListener<AudioEmbedderResult>> resultListener = Optional.empty();
    private Optional<ErrorListener> errorListener = Optional.empty();
    Builder() {
    }
    @Override
    public AudioEmbedder.AudioEmbedderOptions.Builder setBaseOptions(BaseOptions baseOptions) {
      if (baseOptions == null) {
        throw new NullPointerException("Null baseOptions");
      }
      this.baseOptions = baseOptions;
      return this;
    }
    @Override
    public AudioEmbedder.AudioEmbedderOptions.Builder setRunningMode(RunningMode runningMode) {
      if (runningMode == null) {
        throw new NullPointerException("Null runningMode");
      }
      this.runningMode = runningMode;
      return this;
    }
    @Override
    public AudioEmbedder.AudioEmbedderOptions.Builder setL2Normalize(boolean l2Normalize) {
      this.l2Normalize = l2Normalize;
      return this;
    }
    @Override
    public AudioEmbedder.AudioEmbedderOptions.Builder setQuantize(boolean quantize) {
      this.quantize = quantize;
      return this;
    }
    @Override
    public AudioEmbedder.AudioEmbedderOptions.Builder setResultListener(OutputHandler.PureResultListener<AudioEmbedderResult> resultListener) {
      this.resultListener = Optional.of(resultListener);
      return this;
    }
    @Override
    public AudioEmbedder.AudioEmbedderOptions.Builder setErrorListener(ErrorListener errorListener) {
      this.errorListener = Optional.of(errorListener);
      return this;
    }
    @Override
    AudioEmbedder.AudioEmbedderOptions autoBuild() {
      String missing = "";
      if (this.baseOptions == null) {
        missing += " baseOptions";
      }
      if (this.runningMode == null) {
        missing += " runningMode";
      }
      if (this.l2Normalize == null) {
        missing += " l2Normalize";
      }
      if (this.quantize == null) {
        missing += " quantize";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_AudioEmbedder_AudioEmbedderOptions(
          this.baseOptions,
          this.runningMode,
          this.l2Normalize,
          this.quantize,
          this.resultListener,
          this.errorListener);
    }
  }

}
