// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/framework/formats/landmark.proto

package com.google.mediapipe.formats.proto;

public final class LandmarkProto {
  private LandmarkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LandmarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.Landmark)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional float x = 1;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>optional float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>optional float y = 2;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>optional float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>optional float z = 3;</code>
     * @return Whether the z field is set.
     */
    boolean hasZ();
    /**
     * <code>optional float z = 3;</code>
     * @return The z.
     */
    float getZ();

    /**
     * <pre>
     * Landmark visibility. Should stay unset if not supported.
     * Float score of whether landmark is visible or occluded by other objects.
     * Landmark considered as invisible also if it is not present on the screen
     * (out of scene bounds). Depending on the model, visibility value is either a
     * sigmoid or an argument of sigmoid.
     * </pre>
     *
     * <code>optional float visibility = 4;</code>
     * @return Whether the visibility field is set.
     */
    boolean hasVisibility();
    /**
     * <pre>
     * Landmark visibility. Should stay unset if not supported.
     * Float score of whether landmark is visible or occluded by other objects.
     * Landmark considered as invisible also if it is not present on the screen
     * (out of scene bounds). Depending on the model, visibility value is either a
     * sigmoid or an argument of sigmoid.
     * </pre>
     *
     * <code>optional float visibility = 4;</code>
     * @return The visibility.
     */
    float getVisibility();

    /**
     * <pre>
     * Landmark presence. Should stay unset if not supported.
     * Float score of whether landmark is present on the scene (located within
     * scene bounds). Depending on the model, presence value is either a result of
     * sigmoid or an argument of sigmoid function to get landmark presence
     * probability.
     * </pre>
     *
     * <code>optional float presence = 5;</code>
     * @return Whether the presence field is set.
     */
    boolean hasPresence();
    /**
     * <pre>
     * Landmark presence. Should stay unset if not supported.
     * Float score of whether landmark is present on the scene (located within
     * scene bounds). Depending on the model, presence value is either a result of
     * sigmoid or an argument of sigmoid function to get landmark presence
     * probability.
     * </pre>
     *
     * <code>optional float presence = 5;</code>
     * @return The presence.
     */
    float getPresence();
  }
  /**
   * <pre>
   * A landmark that can have 1 to 3 dimensions. Use x for 1D points, (x, y) for
   * 2D points and (x, y, z) for 3D points. For more dimensions, consider using
   * matrix_data.proto.
   * </pre>
   *
   * Protobuf type {@code mediapipe.Landmark}
   */
  public  static final class Landmark extends
      com.google.protobuf.GeneratedMessageLite<
          Landmark, Landmark.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.Landmark)
      LandmarkOrBuilder {
    private Landmark() {
    }
    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>optional float x = 1;</code>
     * @return Whether the x field is set.
     */
    @Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional float x = 1;</code>
     * @return The x.
     */
    @Override
    public float getX() {
      return x_;
    }
    /**
     * <code>optional float x = 1;</code>
     * @param value The x to set.
     */
    private void setX(float value) {
      bitField0_ |= 0x00000001;
      x_ = value;
    }
    /**
     * <code>optional float x = 1;</code>
     */
    private void clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0F;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>optional float y = 2;</code>
     * @return Whether the y field is set.
     */
    @Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float y = 2;</code>
     * @return The y.
     */
    @Override
    public float getY() {
      return y_;
    }
    /**
     * <code>optional float y = 2;</code>
     * @param value The y to set.
     */
    private void setY(float value) {
      bitField0_ |= 0x00000002;
      y_ = value;
    }
    /**
     * <code>optional float y = 2;</code>
     */
    private void clearY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0F;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>optional float z = 3;</code>
     * @return Whether the z field is set.
     */
    @Override
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional float z = 3;</code>
     * @return The z.
     */
    @Override
    public float getZ() {
      return z_;
    }
    /**
     * <code>optional float z = 3;</code>
     * @param value The z to set.
     */
    private void setZ(float value) {
      bitField0_ |= 0x00000004;
      z_ = value;
    }
    /**
     * <code>optional float z = 3;</code>
     */
    private void clearZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      z_ = 0F;
    }

    public static final int VISIBILITY_FIELD_NUMBER = 4;
    private float visibility_;
    /**
     * <pre>
     * Landmark visibility. Should stay unset if not supported.
     * Float score of whether landmark is visible or occluded by other objects.
     * Landmark considered as invisible also if it is not present on the screen
     * (out of scene bounds). Depending on the model, visibility value is either a
     * sigmoid or an argument of sigmoid.
     * </pre>
     *
     * <code>optional float visibility = 4;</code>
     * @return Whether the visibility field is set.
     */
    @Override
    public boolean hasVisibility() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Landmark visibility. Should stay unset if not supported.
     * Float score of whether landmark is visible or occluded by other objects.
     * Landmark considered as invisible also if it is not present on the screen
     * (out of scene bounds). Depending on the model, visibility value is either a
     * sigmoid or an argument of sigmoid.
     * </pre>
     *
     * <code>optional float visibility = 4;</code>
     * @return The visibility.
     */
    @Override
    public float getVisibility() {
      return visibility_;
    }
    /**
     * <pre>
     * Landmark visibility. Should stay unset if not supported.
     * Float score of whether landmark is visible or occluded by other objects.
     * Landmark considered as invisible also if it is not present on the screen
     * (out of scene bounds). Depending on the model, visibility value is either a
     * sigmoid or an argument of sigmoid.
     * </pre>
     *
     * <code>optional float visibility = 4;</code>
     * @param value The visibility to set.
     */
    private void setVisibility(float value) {
      bitField0_ |= 0x00000008;
      visibility_ = value;
    }
    /**
     * <pre>
     * Landmark visibility. Should stay unset if not supported.
     * Float score of whether landmark is visible or occluded by other objects.
     * Landmark considered as invisible also if it is not present on the screen
     * (out of scene bounds). Depending on the model, visibility value is either a
     * sigmoid or an argument of sigmoid.
     * </pre>
     *
     * <code>optional float visibility = 4;</code>
     */
    private void clearVisibility() {
      bitField0_ = (bitField0_ & ~0x00000008);
      visibility_ = 0F;
    }

    public static final int PRESENCE_FIELD_NUMBER = 5;
    private float presence_;
    /**
     * <pre>
     * Landmark presence. Should stay unset if not supported.
     * Float score of whether landmark is present on the scene (located within
     * scene bounds). Depending on the model, presence value is either a result of
     * sigmoid or an argument of sigmoid function to get landmark presence
     * probability.
     * </pre>
     *
     * <code>optional float presence = 5;</code>
     * @return Whether the presence field is set.
     */
    @Override
    public boolean hasPresence() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Landmark presence. Should stay unset if not supported.
     * Float score of whether landmark is present on the scene (located within
     * scene bounds). Depending on the model, presence value is either a result of
     * sigmoid or an argument of sigmoid function to get landmark presence
     * probability.
     * </pre>
     *
     * <code>optional float presence = 5;</code>
     * @return The presence.
     */
    @Override
    public float getPresence() {
      return presence_;
    }
    /**
     * <pre>
     * Landmark presence. Should stay unset if not supported.
     * Float score of whether landmark is present on the scene (located within
     * scene bounds). Depending on the model, presence value is either a result of
     * sigmoid or an argument of sigmoid function to get landmark presence
     * probability.
     * </pre>
     *
     * <code>optional float presence = 5;</code>
     * @param value The presence to set.
     */
    private void setPresence(float value) {
      bitField0_ |= 0x00000010;
      presence_ = value;
    }
    /**
     * <pre>
     * Landmark presence. Should stay unset if not supported.
     * Float score of whether landmark is present on the scene (located within
     * scene bounds). Depending on the model, presence value is either a result of
     * sigmoid or an argument of sigmoid function to get landmark presence
     * probability.
     * </pre>
     *
     * <code>optional float presence = 5;</code>
     */
    private void clearPresence() {
      bitField0_ = (bitField0_ & ~0x00000010);
      presence_ = 0F;
    }

    public static Landmark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Landmark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Landmark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Landmark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Landmark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Landmark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Landmark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Landmark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Landmark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Landmark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Landmark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Landmark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Landmark prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A landmark that can have 1 to 3 dimensions. Use x for 1D points, (x, y) for
     * 2D points and (x, y, z) for 3D points. For more dimensions, consider using
     * matrix_data.proto.
     * </pre>
     *
     * Protobuf type {@code mediapipe.Landmark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Landmark, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.Landmark)
        LandmarkOrBuilder {
      // Construct using com.google.mediapipe.formats.proto.LandmarkProto.Landmark.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional float x = 1;</code>
       * @return Whether the x field is set.
       */
      @Override
      public boolean hasX() {
        return instance.hasX();
      }
      /**
       * <code>optional float x = 1;</code>
       * @return The x.
       */
      @Override
      public float getX() {
        return instance.getX();
      }
      /**
       * <code>optional float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        copyOnWrite();
        instance.setX(value);
        return this;
      }
      /**
       * <code>optional float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        copyOnWrite();
        instance.clearX();
        return this;
      }

      /**
       * <code>optional float y = 2;</code>
       * @return Whether the y field is set.
       */
      @Override
      public boolean hasY() {
        return instance.hasY();
      }
      /**
       * <code>optional float y = 2;</code>
       * @return The y.
       */
      @Override
      public float getY() {
        return instance.getY();
      }
      /**
       * <code>optional float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        copyOnWrite();
        instance.setY(value);
        return this;
      }
      /**
       * <code>optional float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        copyOnWrite();
        instance.clearY();
        return this;
      }

      /**
       * <code>optional float z = 3;</code>
       * @return Whether the z field is set.
       */
      @Override
      public boolean hasZ() {
        return instance.hasZ();
      }
      /**
       * <code>optional float z = 3;</code>
       * @return The z.
       */
      @Override
      public float getZ() {
        return instance.getZ();
      }
      /**
       * <code>optional float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {
        copyOnWrite();
        instance.setZ(value);
        return this;
      }
      /**
       * <code>optional float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        copyOnWrite();
        instance.clearZ();
        return this;
      }

      /**
       * <pre>
       * Landmark visibility. Should stay unset if not supported.
       * Float score of whether landmark is visible or occluded by other objects.
       * Landmark considered as invisible also if it is not present on the screen
       * (out of scene bounds). Depending on the model, visibility value is either a
       * sigmoid or an argument of sigmoid.
       * </pre>
       *
       * <code>optional float visibility = 4;</code>
       * @return Whether the visibility field is set.
       */
      @Override
      public boolean hasVisibility() {
        return instance.hasVisibility();
      }
      /**
       * <pre>
       * Landmark visibility. Should stay unset if not supported.
       * Float score of whether landmark is visible or occluded by other objects.
       * Landmark considered as invisible also if it is not present on the screen
       * (out of scene bounds). Depending on the model, visibility value is either a
       * sigmoid or an argument of sigmoid.
       * </pre>
       *
       * <code>optional float visibility = 4;</code>
       * @return The visibility.
       */
      @Override
      public float getVisibility() {
        return instance.getVisibility();
      }
      /**
       * <pre>
       * Landmark visibility. Should stay unset if not supported.
       * Float score of whether landmark is visible or occluded by other objects.
       * Landmark considered as invisible also if it is not present on the screen
       * (out of scene bounds). Depending on the model, visibility value is either a
       * sigmoid or an argument of sigmoid.
       * </pre>
       *
       * <code>optional float visibility = 4;</code>
       * @param value The visibility to set.
       * @return This builder for chaining.
       */
      public Builder setVisibility(float value) {
        copyOnWrite();
        instance.setVisibility(value);
        return this;
      }
      /**
       * <pre>
       * Landmark visibility. Should stay unset if not supported.
       * Float score of whether landmark is visible or occluded by other objects.
       * Landmark considered as invisible also if it is not present on the screen
       * (out of scene bounds). Depending on the model, visibility value is either a
       * sigmoid or an argument of sigmoid.
       * </pre>
       *
       * <code>optional float visibility = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVisibility() {
        copyOnWrite();
        instance.clearVisibility();
        return this;
      }

      /**
       * <pre>
       * Landmark presence. Should stay unset if not supported.
       * Float score of whether landmark is present on the scene (located within
       * scene bounds). Depending on the model, presence value is either a result of
       * sigmoid or an argument of sigmoid function to get landmark presence
       * probability.
       * </pre>
       *
       * <code>optional float presence = 5;</code>
       * @return Whether the presence field is set.
       */
      @Override
      public boolean hasPresence() {
        return instance.hasPresence();
      }
      /**
       * <pre>
       * Landmark presence. Should stay unset if not supported.
       * Float score of whether landmark is present on the scene (located within
       * scene bounds). Depending on the model, presence value is either a result of
       * sigmoid or an argument of sigmoid function to get landmark presence
       * probability.
       * </pre>
       *
       * <code>optional float presence = 5;</code>
       * @return The presence.
       */
      @Override
      public float getPresence() {
        return instance.getPresence();
      }
      /**
       * <pre>
       * Landmark presence. Should stay unset if not supported.
       * Float score of whether landmark is present on the scene (located within
       * scene bounds). Depending on the model, presence value is either a result of
       * sigmoid or an argument of sigmoid function to get landmark presence
       * probability.
       * </pre>
       *
       * <code>optional float presence = 5;</code>
       * @param value The presence to set.
       * @return This builder for chaining.
       */
      public Builder setPresence(float value) {
        copyOnWrite();
        instance.setPresence(value);
        return this;
      }
      /**
       * <pre>
       * Landmark presence. Should stay unset if not supported.
       * Float score of whether landmark is present on the scene (located within
       * scene bounds). Depending on the model, presence value is either a result of
       * sigmoid or an argument of sigmoid function to get landmark presence
       * probability.
       * </pre>
       *
       * <code>optional float presence = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPresence() {
        copyOnWrite();
        instance.clearPresence();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.Landmark)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Landmark();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "x_",
              "y_",
              "z_",
              "visibility_",
              "presence_",
            };
            String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1001\u0000\u0002" +
                "\u1001\u0001\u0003\u1001\u0002\u0004\u1001\u0003\u0005\u1001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Landmark> parser = PARSER;
          if (parser == null) {
            synchronized (Landmark.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Landmark>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.Landmark)
    private static final Landmark DEFAULT_INSTANCE;
    static {
      Landmark defaultInstance = new Landmark();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Landmark.class, defaultInstance);
    }

    public static Landmark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Landmark> PARSER;

    public static com.google.protobuf.Parser<Landmark> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LandmarkListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.LandmarkList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    java.util.List<Landmark>
        getLandmarkList();
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    Landmark getLandmark(int index);
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    int getLandmarkCount();
  }
  /**
   * <pre>
   * Group of Landmark protos.
   * </pre>
   *
   * Protobuf type {@code mediapipe.LandmarkList}
   */
  public  static final class LandmarkList extends
      com.google.protobuf.GeneratedMessageLite<
          LandmarkList, LandmarkList.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.LandmarkList)
      LandmarkListOrBuilder {
    private LandmarkList() {
      landmark_ = emptyProtobufList();
    }
    public static final int LANDMARK_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Landmark> landmark_;
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    @Override
    public java.util.List<Landmark> getLandmarkList() {
      return landmark_;
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    public java.util.List<? extends LandmarkOrBuilder>
        getLandmarkOrBuilderList() {
      return landmark_;
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    @Override
    public int getLandmarkCount() {
      return landmark_.size();
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    @Override
    public Landmark getLandmark(int index) {
      return landmark_.get(index);
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    public LandmarkOrBuilder getLandmarkOrBuilder(
        int index) {
      return landmark_.get(index);
    }
    private void ensureLandmarkIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Landmark> tmp = landmark_;
      if (!tmp.isModifiable()) {
        landmark_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    private void setLandmark(
        int index, Landmark value) {
      value.getClass();
  ensureLandmarkIsMutable();
      landmark_.set(index, value);
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    private void addLandmark(Landmark value) {
      value.getClass();
  ensureLandmarkIsMutable();
      landmark_.add(value);
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    private void addLandmark(
        int index, Landmark value) {
      value.getClass();
  ensureLandmarkIsMutable();
      landmark_.add(index, value);
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    private void addAllLandmark(
        Iterable<? extends Landmark> values) {
      ensureLandmarkIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, landmark_);
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    private void clearLandmark() {
      landmark_ = emptyProtobufList();
    }
    /**
     * <code>repeated .mediapipe.Landmark landmark = 1;</code>
     */
    private void removeLandmark(int index) {
      ensureLandmarkIsMutable();
      landmark_.remove(index);
    }

    public static LandmarkList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LandmarkList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LandmarkList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LandmarkList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LandmarkList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LandmarkList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LandmarkList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LandmarkList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LandmarkList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LandmarkList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LandmarkList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LandmarkList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LandmarkList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Group of Landmark protos.
     * </pre>
     *
     * Protobuf type {@code mediapipe.LandmarkList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LandmarkList, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.LandmarkList)
        LandmarkListOrBuilder {
      // Construct using com.google.mediapipe.formats.proto.LandmarkProto.LandmarkList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      @Override
      public java.util.List<Landmark> getLandmarkList() {
        return java.util.Collections.unmodifiableList(
            instance.getLandmarkList());
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      @Override
      public int getLandmarkCount() {
        return instance.getLandmarkCount();
      }/**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      @Override
      public Landmark getLandmark(int index) {
        return instance.getLandmark(index);
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder setLandmark(
          int index, Landmark value) {
        copyOnWrite();
        instance.setLandmark(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder setLandmark(
          int index, Landmark.Builder builderForValue) {
        copyOnWrite();
        instance.setLandmark(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder addLandmark(Landmark value) {
        copyOnWrite();
        instance.addLandmark(value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder addLandmark(
          int index, Landmark value) {
        copyOnWrite();
        instance.addLandmark(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder addLandmark(
          Landmark.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmark(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder addLandmark(
          int index, Landmark.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmark(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder addAllLandmark(
          Iterable<? extends Landmark> values) {
        copyOnWrite();
        instance.addAllLandmark(values);
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder clearLandmark() {
        copyOnWrite();
        instance.clearLandmark();
        return this;
      }
      /**
       * <code>repeated .mediapipe.Landmark landmark = 1;</code>
       */
      public Builder removeLandmark(int index) {
        copyOnWrite();
        instance.removeLandmark(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.LandmarkList)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LandmarkList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "landmark_",
              Landmark.class,
            };
            String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LandmarkList> parser = PARSER;
          if (parser == null) {
            synchronized (LandmarkList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LandmarkList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.LandmarkList)
    private static final LandmarkList DEFAULT_INSTANCE;
    static {
      LandmarkList defaultInstance = new LandmarkList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LandmarkList.class, defaultInstance);
    }

    public static LandmarkList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LandmarkList> PARSER;

    public static com.google.protobuf.Parser<LandmarkList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LandmarkListCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.LandmarkListCollection)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    java.util.List<LandmarkList>
        getLandmarkListList();
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    LandmarkList getLandmarkList(int index);
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    int getLandmarkListCount();
  }
  /**
   * <pre>
   * Group of LandmarkList protos.
   * </pre>
   *
   * Protobuf type {@code mediapipe.LandmarkListCollection}
   */
  public  static final class LandmarkListCollection extends
      com.google.protobuf.GeneratedMessageLite<
          LandmarkListCollection, LandmarkListCollection.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.LandmarkListCollection)
      LandmarkListCollectionOrBuilder {
    private LandmarkListCollection() {
      landmarkList_ = emptyProtobufList();
    }
    public static final int LANDMARK_LIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<LandmarkList> landmarkList_;
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    @Override
    public java.util.List<LandmarkList> getLandmarkListList() {
      return landmarkList_;
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    public java.util.List<? extends LandmarkListOrBuilder>
        getLandmarkListOrBuilderList() {
      return landmarkList_;
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    @Override
    public int getLandmarkListCount() {
      return landmarkList_.size();
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    @Override
    public LandmarkList getLandmarkList(int index) {
      return landmarkList_.get(index);
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    public LandmarkListOrBuilder getLandmarkListOrBuilder(
        int index) {
      return landmarkList_.get(index);
    }
    private void ensureLandmarkListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<LandmarkList> tmp = landmarkList_;
      if (!tmp.isModifiable()) {
        landmarkList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    private void setLandmarkList(
        int index, LandmarkList value) {
      value.getClass();
  ensureLandmarkListIsMutable();
      landmarkList_.set(index, value);
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    private void addLandmarkList(LandmarkList value) {
      value.getClass();
  ensureLandmarkListIsMutable();
      landmarkList_.add(value);
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    private void addLandmarkList(
        int index, LandmarkList value) {
      value.getClass();
  ensureLandmarkListIsMutable();
      landmarkList_.add(index, value);
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    private void addAllLandmarkList(
        Iterable<? extends LandmarkList> values) {
      ensureLandmarkListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, landmarkList_);
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    private void clearLandmarkList() {
      landmarkList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
     */
    private void removeLandmarkList(int index) {
      ensureLandmarkListIsMutable();
      landmarkList_.remove(index);
    }

    public static LandmarkListCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LandmarkListCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LandmarkListCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LandmarkListCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LandmarkListCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LandmarkListCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LandmarkListCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LandmarkListCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LandmarkListCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LandmarkListCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LandmarkListCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LandmarkListCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LandmarkListCollection prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Group of LandmarkList protos.
     * </pre>
     *
     * Protobuf type {@code mediapipe.LandmarkListCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LandmarkListCollection, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.LandmarkListCollection)
        LandmarkListCollectionOrBuilder {
      // Construct using com.google.mediapipe.formats.proto.LandmarkProto.LandmarkListCollection.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      @Override
      public java.util.List<LandmarkList> getLandmarkListList() {
        return java.util.Collections.unmodifiableList(
            instance.getLandmarkListList());
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      @Override
      public int getLandmarkListCount() {
        return instance.getLandmarkListCount();
      }/**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      @Override
      public LandmarkList getLandmarkList(int index) {
        return instance.getLandmarkList(index);
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder setLandmarkList(
          int index, LandmarkList value) {
        copyOnWrite();
        instance.setLandmarkList(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder setLandmarkList(
          int index, LandmarkList.Builder builderForValue) {
        copyOnWrite();
        instance.setLandmarkList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(LandmarkList value) {
        copyOnWrite();
        instance.addLandmarkList(value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(
          int index, LandmarkList value) {
        copyOnWrite();
        instance.addLandmarkList(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(
          LandmarkList.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmarkList(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(
          int index, LandmarkList.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmarkList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder addAllLandmarkList(
          Iterable<? extends LandmarkList> values) {
        copyOnWrite();
        instance.addAllLandmarkList(values);
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder clearLandmarkList() {
        copyOnWrite();
        instance.clearLandmarkList();
        return this;
      }
      /**
       * <code>repeated .mediapipe.LandmarkList landmark_list = 1;</code>
       */
      public Builder removeLandmarkList(int index) {
        copyOnWrite();
        instance.removeLandmarkList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.LandmarkListCollection)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LandmarkListCollection();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "landmarkList_",
              LandmarkList.class,
            };
            String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LandmarkListCollection> parser = PARSER;
          if (parser == null) {
            synchronized (LandmarkListCollection.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LandmarkListCollection>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.LandmarkListCollection)
    private static final LandmarkListCollection DEFAULT_INSTANCE;
    static {
      LandmarkListCollection defaultInstance = new LandmarkListCollection();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LandmarkListCollection.class, defaultInstance);
    }

    public static LandmarkListCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LandmarkListCollection> PARSER;

    public static com.google.protobuf.Parser<LandmarkListCollection> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NormalizedLandmarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.NormalizedLandmark)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional float x = 1;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>optional float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>optional float y = 2;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>optional float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>optional float z = 3;</code>
     * @return Whether the z field is set.
     */
    boolean hasZ();
    /**
     * <code>optional float z = 3;</code>
     * @return The z.
     */
    float getZ();

    /**
     * <code>optional float visibility = 4;</code>
     * @return Whether the visibility field is set.
     */
    boolean hasVisibility();
    /**
     * <code>optional float visibility = 4;</code>
     * @return The visibility.
     */
    float getVisibility();

    /**
     * <code>optional float presence = 5;</code>
     * @return Whether the presence field is set.
     */
    boolean hasPresence();
    /**
     * <code>optional float presence = 5;</code>
     * @return The presence.
     */
    float getPresence();
  }
  /**
   * <pre>
   * A normalized version of above Landmark proto. All coordinates should be
   * within [0, 1].
   * </pre>
   *
   * Protobuf type {@code mediapipe.NormalizedLandmark}
   */
  public  static final class NormalizedLandmark extends
      com.google.protobuf.GeneratedMessageLite<
          NormalizedLandmark, NormalizedLandmark.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.NormalizedLandmark)
      NormalizedLandmarkOrBuilder {
    private NormalizedLandmark() {
    }
    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>optional float x = 1;</code>
     * @return Whether the x field is set.
     */
    @Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional float x = 1;</code>
     * @return The x.
     */
    @Override
    public float getX() {
      return x_;
    }
    /**
     * <code>optional float x = 1;</code>
     * @param value The x to set.
     */
    private void setX(float value) {
      bitField0_ |= 0x00000001;
      x_ = value;
    }
    /**
     * <code>optional float x = 1;</code>
     */
    private void clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0F;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>optional float y = 2;</code>
     * @return Whether the y field is set.
     */
    @Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float y = 2;</code>
     * @return The y.
     */
    @Override
    public float getY() {
      return y_;
    }
    /**
     * <code>optional float y = 2;</code>
     * @param value The y to set.
     */
    private void setY(float value) {
      bitField0_ |= 0x00000002;
      y_ = value;
    }
    /**
     * <code>optional float y = 2;</code>
     */
    private void clearY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0F;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>optional float z = 3;</code>
     * @return Whether the z field is set.
     */
    @Override
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional float z = 3;</code>
     * @return The z.
     */
    @Override
    public float getZ() {
      return z_;
    }
    /**
     * <code>optional float z = 3;</code>
     * @param value The z to set.
     */
    private void setZ(float value) {
      bitField0_ |= 0x00000004;
      z_ = value;
    }
    /**
     * <code>optional float z = 3;</code>
     */
    private void clearZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      z_ = 0F;
    }

    public static final int VISIBILITY_FIELD_NUMBER = 4;
    private float visibility_;
    /**
     * <code>optional float visibility = 4;</code>
     * @return Whether the visibility field is set.
     */
    @Override
    public boolean hasVisibility() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional float visibility = 4;</code>
     * @return The visibility.
     */
    @Override
    public float getVisibility() {
      return visibility_;
    }
    /**
     * <code>optional float visibility = 4;</code>
     * @param value The visibility to set.
     */
    private void setVisibility(float value) {
      bitField0_ |= 0x00000008;
      visibility_ = value;
    }
    /**
     * <code>optional float visibility = 4;</code>
     */
    private void clearVisibility() {
      bitField0_ = (bitField0_ & ~0x00000008);
      visibility_ = 0F;
    }

    public static final int PRESENCE_FIELD_NUMBER = 5;
    private float presence_;
    /**
     * <code>optional float presence = 5;</code>
     * @return Whether the presence field is set.
     */
    @Override
    public boolean hasPresence() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional float presence = 5;</code>
     * @return The presence.
     */
    @Override
    public float getPresence() {
      return presence_;
    }
    /**
     * <code>optional float presence = 5;</code>
     * @param value The presence to set.
     */
    private void setPresence(float value) {
      bitField0_ |= 0x00000010;
      presence_ = value;
    }
    /**
     * <code>optional float presence = 5;</code>
     */
    private void clearPresence() {
      bitField0_ = (bitField0_ & ~0x00000010);
      presence_ = 0F;
    }

    public static NormalizedLandmark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NormalizedLandmark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NormalizedLandmark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(NormalizedLandmark prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A normalized version of above Landmark proto. All coordinates should be
     * within [0, 1].
     * </pre>
     *
     * Protobuf type {@code mediapipe.NormalizedLandmark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NormalizedLandmark, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.NormalizedLandmark)
        NormalizedLandmarkOrBuilder {
      // Construct using com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional float x = 1;</code>
       * @return Whether the x field is set.
       */
      @Override
      public boolean hasX() {
        return instance.hasX();
      }
      /**
       * <code>optional float x = 1;</code>
       * @return The x.
       */
      @Override
      public float getX() {
        return instance.getX();
      }
      /**
       * <code>optional float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        copyOnWrite();
        instance.setX(value);
        return this;
      }
      /**
       * <code>optional float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        copyOnWrite();
        instance.clearX();
        return this;
      }

      /**
       * <code>optional float y = 2;</code>
       * @return Whether the y field is set.
       */
      @Override
      public boolean hasY() {
        return instance.hasY();
      }
      /**
       * <code>optional float y = 2;</code>
       * @return The y.
       */
      @Override
      public float getY() {
        return instance.getY();
      }
      /**
       * <code>optional float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        copyOnWrite();
        instance.setY(value);
        return this;
      }
      /**
       * <code>optional float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        copyOnWrite();
        instance.clearY();
        return this;
      }

      /**
       * <code>optional float z = 3;</code>
       * @return Whether the z field is set.
       */
      @Override
      public boolean hasZ() {
        return instance.hasZ();
      }
      /**
       * <code>optional float z = 3;</code>
       * @return The z.
       */
      @Override
      public float getZ() {
        return instance.getZ();
      }
      /**
       * <code>optional float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {
        copyOnWrite();
        instance.setZ(value);
        return this;
      }
      /**
       * <code>optional float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        copyOnWrite();
        instance.clearZ();
        return this;
      }

      /**
       * <code>optional float visibility = 4;</code>
       * @return Whether the visibility field is set.
       */
      @Override
      public boolean hasVisibility() {
        return instance.hasVisibility();
      }
      /**
       * <code>optional float visibility = 4;</code>
       * @return The visibility.
       */
      @Override
      public float getVisibility() {
        return instance.getVisibility();
      }
      /**
       * <code>optional float visibility = 4;</code>
       * @param value The visibility to set.
       * @return This builder for chaining.
       */
      public Builder setVisibility(float value) {
        copyOnWrite();
        instance.setVisibility(value);
        return this;
      }
      /**
       * <code>optional float visibility = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVisibility() {
        copyOnWrite();
        instance.clearVisibility();
        return this;
      }

      /**
       * <code>optional float presence = 5;</code>
       * @return Whether the presence field is set.
       */
      @Override
      public boolean hasPresence() {
        return instance.hasPresence();
      }
      /**
       * <code>optional float presence = 5;</code>
       * @return The presence.
       */
      @Override
      public float getPresence() {
        return instance.getPresence();
      }
      /**
       * <code>optional float presence = 5;</code>
       * @param value The presence to set.
       * @return This builder for chaining.
       */
      public Builder setPresence(float value) {
        copyOnWrite();
        instance.setPresence(value);
        return this;
      }
      /**
       * <code>optional float presence = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPresence() {
        copyOnWrite();
        instance.clearPresence();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.NormalizedLandmark)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new NormalizedLandmark();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "x_",
              "y_",
              "z_",
              "visibility_",
              "presence_",
            };
            String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1001\u0000\u0002" +
                "\u1001\u0001\u0003\u1001\u0002\u0004\u1001\u0003\u0005\u1001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<NormalizedLandmark> parser = PARSER;
          if (parser == null) {
            synchronized (NormalizedLandmark.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<NormalizedLandmark>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.NormalizedLandmark)
    private static final NormalizedLandmark DEFAULT_INSTANCE;
    static {
      NormalizedLandmark defaultInstance = new NormalizedLandmark();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NormalizedLandmark.class, defaultInstance);
    }

    public static NormalizedLandmark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NormalizedLandmark> PARSER;

    public static com.google.protobuf.Parser<NormalizedLandmark> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NormalizedLandmarkListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.NormalizedLandmarkList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    java.util.List<NormalizedLandmark>
        getLandmarkList();
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    NormalizedLandmark getLandmark(int index);
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    int getLandmarkCount();
  }
  /**
   * <pre>
   * Group of NormalizedLandmark protos.
   * </pre>
   *
   * Protobuf type {@code mediapipe.NormalizedLandmarkList}
   */
  public  static final class NormalizedLandmarkList extends
      com.google.protobuf.GeneratedMessageLite<
          NormalizedLandmarkList, NormalizedLandmarkList.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.NormalizedLandmarkList)
      NormalizedLandmarkListOrBuilder {
    private NormalizedLandmarkList() {
      landmark_ = emptyProtobufList();
    }
    public static final int LANDMARK_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<NormalizedLandmark> landmark_;
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    @Override
    public java.util.List<NormalizedLandmark> getLandmarkList() {
      return landmark_;
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    public java.util.List<? extends NormalizedLandmarkOrBuilder>
        getLandmarkOrBuilderList() {
      return landmark_;
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    @Override
    public int getLandmarkCount() {
      return landmark_.size();
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    @Override
    public NormalizedLandmark getLandmark(int index) {
      return landmark_.get(index);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    public NormalizedLandmarkOrBuilder getLandmarkOrBuilder(
        int index) {
      return landmark_.get(index);
    }
    private void ensureLandmarkIsMutable() {
      com.google.protobuf.Internal.ProtobufList<NormalizedLandmark> tmp = landmark_;
      if (!tmp.isModifiable()) {
        landmark_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    private void setLandmark(
        int index, NormalizedLandmark value) {
      value.getClass();
  ensureLandmarkIsMutable();
      landmark_.set(index, value);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    private void addLandmark(NormalizedLandmark value) {
      value.getClass();
  ensureLandmarkIsMutable();
      landmark_.add(value);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    private void addLandmark(
        int index, NormalizedLandmark value) {
      value.getClass();
  ensureLandmarkIsMutable();
      landmark_.add(index, value);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    private void addAllLandmark(
        Iterable<? extends NormalizedLandmark> values) {
      ensureLandmarkIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, landmark_);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    private void clearLandmark() {
      landmark_ = emptyProtobufList();
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
     */
    private void removeLandmark(int index) {
      ensureLandmarkIsMutable();
      landmark_.remove(index);
    }

    public static NormalizedLandmarkList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmarkList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmarkList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmarkList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmarkList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmarkList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmarkList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmarkList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NormalizedLandmarkList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmarkList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NormalizedLandmarkList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmarkList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(NormalizedLandmarkList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Group of NormalizedLandmark protos.
     * </pre>
     *
     * Protobuf type {@code mediapipe.NormalizedLandmarkList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NormalizedLandmarkList, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.NormalizedLandmarkList)
        NormalizedLandmarkListOrBuilder {
      // Construct using com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      @Override
      public java.util.List<NormalizedLandmark> getLandmarkList() {
        return java.util.Collections.unmodifiableList(
            instance.getLandmarkList());
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      @Override
      public int getLandmarkCount() {
        return instance.getLandmarkCount();
      }/**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      @Override
      public NormalizedLandmark getLandmark(int index) {
        return instance.getLandmark(index);
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder setLandmark(
          int index, NormalizedLandmark value) {
        copyOnWrite();
        instance.setLandmark(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder setLandmark(
          int index, NormalizedLandmark.Builder builderForValue) {
        copyOnWrite();
        instance.setLandmark(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder addLandmark(NormalizedLandmark value) {
        copyOnWrite();
        instance.addLandmark(value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder addLandmark(
          int index, NormalizedLandmark value) {
        copyOnWrite();
        instance.addLandmark(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder addLandmark(
          NormalizedLandmark.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmark(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder addLandmark(
          int index, NormalizedLandmark.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmark(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder addAllLandmark(
          Iterable<? extends NormalizedLandmark> values) {
        copyOnWrite();
        instance.addAllLandmark(values);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder clearLandmark() {
        copyOnWrite();
        instance.clearLandmark();
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmark landmark = 1;</code>
       */
      public Builder removeLandmark(int index) {
        copyOnWrite();
        instance.removeLandmark(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.NormalizedLandmarkList)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new NormalizedLandmarkList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "landmark_",
              NormalizedLandmark.class,
            };
            String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<NormalizedLandmarkList> parser = PARSER;
          if (parser == null) {
            synchronized (NormalizedLandmarkList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<NormalizedLandmarkList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.NormalizedLandmarkList)
    private static final NormalizedLandmarkList DEFAULT_INSTANCE;
    static {
      NormalizedLandmarkList defaultInstance = new NormalizedLandmarkList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NormalizedLandmarkList.class, defaultInstance);
    }

    public static NormalizedLandmarkList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NormalizedLandmarkList> PARSER;

    public static com.google.protobuf.Parser<NormalizedLandmarkList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NormalizedLandmarkListCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.NormalizedLandmarkListCollection)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    java.util.List<NormalizedLandmarkList>
        getLandmarkListList();
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    NormalizedLandmarkList getLandmarkList(int index);
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    int getLandmarkListCount();
  }
  /**
   * <pre>
   * Group of NormalizedLandmarkList protos.
   * </pre>
   *
   * Protobuf type {@code mediapipe.NormalizedLandmarkListCollection}
   */
  public  static final class NormalizedLandmarkListCollection extends
      com.google.protobuf.GeneratedMessageLite<
          NormalizedLandmarkListCollection, NormalizedLandmarkListCollection.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.NormalizedLandmarkListCollection)
      NormalizedLandmarkListCollectionOrBuilder {
    private NormalizedLandmarkListCollection() {
      landmarkList_ = emptyProtobufList();
    }
    public static final int LANDMARK_LIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<NormalizedLandmarkList> landmarkList_;
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    @Override
    public java.util.List<NormalizedLandmarkList> getLandmarkListList() {
      return landmarkList_;
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    public java.util.List<? extends NormalizedLandmarkListOrBuilder>
        getLandmarkListOrBuilderList() {
      return landmarkList_;
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    @Override
    public int getLandmarkListCount() {
      return landmarkList_.size();
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    @Override
    public NormalizedLandmarkList getLandmarkList(int index) {
      return landmarkList_.get(index);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    public NormalizedLandmarkListOrBuilder getLandmarkListOrBuilder(
        int index) {
      return landmarkList_.get(index);
    }
    private void ensureLandmarkListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<NormalizedLandmarkList> tmp = landmarkList_;
      if (!tmp.isModifiable()) {
        landmarkList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    private void setLandmarkList(
        int index, NormalizedLandmarkList value) {
      value.getClass();
  ensureLandmarkListIsMutable();
      landmarkList_.set(index, value);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    private void addLandmarkList(NormalizedLandmarkList value) {
      value.getClass();
  ensureLandmarkListIsMutable();
      landmarkList_.add(value);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    private void addLandmarkList(
        int index, NormalizedLandmarkList value) {
      value.getClass();
  ensureLandmarkListIsMutable();
      landmarkList_.add(index, value);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    private void addAllLandmarkList(
        Iterable<? extends NormalizedLandmarkList> values) {
      ensureLandmarkListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, landmarkList_);
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    private void clearLandmarkList() {
      landmarkList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
     */
    private void removeLandmarkList(int index) {
      ensureLandmarkListIsMutable();
      landmarkList_.remove(index);
    }

    public static NormalizedLandmarkListCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmarkListCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NormalizedLandmarkListCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NormalizedLandmarkListCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmarkListCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NormalizedLandmarkListCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(NormalizedLandmarkListCollection prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Group of NormalizedLandmarkList protos.
     * </pre>
     *
     * Protobuf type {@code mediapipe.NormalizedLandmarkListCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NormalizedLandmarkListCollection, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.NormalizedLandmarkListCollection)
        NormalizedLandmarkListCollectionOrBuilder {
      // Construct using com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkListCollection.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      @Override
      public java.util.List<NormalizedLandmarkList> getLandmarkListList() {
        return java.util.Collections.unmodifiableList(
            instance.getLandmarkListList());
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      @Override
      public int getLandmarkListCount() {
        return instance.getLandmarkListCount();
      }/**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      @Override
      public NormalizedLandmarkList getLandmarkList(int index) {
        return instance.getLandmarkList(index);
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder setLandmarkList(
          int index, NormalizedLandmarkList value) {
        copyOnWrite();
        instance.setLandmarkList(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder setLandmarkList(
          int index, NormalizedLandmarkList.Builder builderForValue) {
        copyOnWrite();
        instance.setLandmarkList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(NormalizedLandmarkList value) {
        copyOnWrite();
        instance.addLandmarkList(value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(
          int index, NormalizedLandmarkList value) {
        copyOnWrite();
        instance.addLandmarkList(index, value);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(
          NormalizedLandmarkList.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmarkList(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder addLandmarkList(
          int index, NormalizedLandmarkList.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmarkList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder addAllLandmarkList(
          Iterable<? extends NormalizedLandmarkList> values) {
        copyOnWrite();
        instance.addAllLandmarkList(values);
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder clearLandmarkList() {
        copyOnWrite();
        instance.clearLandmarkList();
        return this;
      }
      /**
       * <code>repeated .mediapipe.NormalizedLandmarkList landmark_list = 1;</code>
       */
      public Builder removeLandmarkList(int index) {
        copyOnWrite();
        instance.removeLandmarkList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.NormalizedLandmarkListCollection)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new NormalizedLandmarkListCollection();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "landmarkList_",
              NormalizedLandmarkList.class,
            };
            String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<NormalizedLandmarkListCollection> parser = PARSER;
          if (parser == null) {
            synchronized (NormalizedLandmarkListCollection.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<NormalizedLandmarkListCollection>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.NormalizedLandmarkListCollection)
    private static final NormalizedLandmarkListCollection DEFAULT_INSTANCE;
    static {
      NormalizedLandmarkListCollection defaultInstance = new NormalizedLandmarkListCollection();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NormalizedLandmarkListCollection.class, defaultInstance);
    }

    public static NormalizedLandmarkListCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NormalizedLandmarkListCollection> PARSER;

    public static com.google.protobuf.Parser<NormalizedLandmarkListCollection> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
