// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/tasks/cc/vision/image_segmenter/proto/segmenter_options.proto

package com.google.mediapipe.tasks.vision.imagesegmenter.proto;

public final class SegmenterOptionsProto {
  private SegmenterOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SegmenterOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
     * @return Whether the outputType field is set.
     */
    boolean hasOutputType();
    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
     * @return The outputType.
     */
    SegmenterOptions.OutputType getOutputType();

    /**
     * <pre>
     * Activation function to apply to input tensor.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
     * @return Whether the activation field is set.
     */
    boolean hasActivation();
    /**
     * <pre>
     * Activation function to apply to input tensor.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
     * @return The activation.
     */
    SegmenterOptions.Activation getActivation();
  }
  /**
   * <pre>
   * Shared options used by image segmentation tasks.
   * </pre>
   *
   * Protobuf type {@code mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions}
   */
  public  static final class SegmenterOptions extends
      com.google.protobuf.GeneratedMessageLite<
          SegmenterOptions, SegmenterOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions)
      SegmenterOptionsOrBuilder {
    private SegmenterOptions() {
      outputType_ = 1;
    }
    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * Protobuf enum {@code mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType}
     */
    public enum OutputType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      UNSPECIFIED(0),
      /**
       * <pre>
       * Gives a single output mask where each pixel represents the class which
       * the pixel in the original image was predicted to belong to.
       * </pre>
       *
       * <code>CATEGORY_MASK = 1;</code>
       */
      CATEGORY_MASK(1),
      /**
       * <pre>
       * Gives a list of output masks where, for each mask, each pixel represents
       * the prediction confidence, usually in the [0, 1] range.
       * </pre>
       *
       * <code>CONFIDENCE_MASK = 2;</code>
       */
      CONFIDENCE_MASK(2),
      ;

      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      public static final int UNSPECIFIED_VALUE = 0;
      /**
       * <pre>
       * Gives a single output mask where each pixel represents the class which
       * the pixel in the original image was predicted to belong to.
       * </pre>
       *
       * <code>CATEGORY_MASK = 1;</code>
       */
      public static final int CATEGORY_MASK_VALUE = 1;
      /**
       * <pre>
       * Gives a list of output masks where, for each mask, each pixel represents
       * the prediction confidence, usually in the [0, 1] range.
       * </pre>
       *
       * <code>CONFIDENCE_MASK = 2;</code>
       */
      public static final int CONFIDENCE_MASK_VALUE = 2;


      @Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static OutputType valueOf(int value) {
        return forNumber(value);
      }

      public static OutputType forNumber(int value) {
        switch (value) {
          case 0: return UNSPECIFIED;
          case 1: return CATEGORY_MASK;
          case 2: return CONFIDENCE_MASK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OutputType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OutputType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OutputType>() {
              @Override
              public OutputType findValueByNumber(int number) {
                return OutputType.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return OutputTypeVerifier.INSTANCE;
      }

      private static final class OutputTypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new OutputTypeVerifier();
              @Override
              public boolean isInRange(int number) {
                return OutputType.forNumber(number) != null;
              }
            };

      private final int value;

      private OutputType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType)
    }

    /**
     * <pre>
     * Supported activation functions for filtering.
     * </pre>
     *
     * Protobuf enum {@code mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation}
     */
    public enum Activation
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <pre>
       * Assumes 1-channel input tensor.
       * </pre>
       *
       * <code>SIGMOID = 1;</code>
       */
      SIGMOID(1),
      /**
       * <pre>
       * Assumes multi-channel input tensor.
       * </pre>
       *
       * <code>SOFTMAX = 2;</code>
       */
      SOFTMAX(2),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <pre>
       * Assumes 1-channel input tensor.
       * </pre>
       *
       * <code>SIGMOID = 1;</code>
       */
      public static final int SIGMOID_VALUE = 1;
      /**
       * <pre>
       * Assumes multi-channel input tensor.
       * </pre>
       *
       * <code>SOFTMAX = 2;</code>
       */
      public static final int SOFTMAX_VALUE = 2;


      @Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Activation valueOf(int value) {
        return forNumber(value);
      }

      public static Activation forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return SIGMOID;
          case 2: return SOFTMAX;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Activation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Activation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Activation>() {
              @Override
              public Activation findValueByNumber(int number) {
                return Activation.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return ActivationVerifier.INSTANCE;
      }

      private static final class ActivationVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ActivationVerifier();
              @Override
              public boolean isInRange(int number) {
                return Activation.forNumber(number) != null;
              }
            };

      private final int value;

      private Activation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation)
    }

    private int bitField0_;
    public static final int OUTPUT_TYPE_FIELD_NUMBER = 1;
    private int outputType_;
    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
     * @return Whether the outputType field is set.
     */
    @Override
    public boolean hasOutputType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
     * @return The outputType.
     */
    @Override
    public OutputType getOutputType() {
      OutputType result = OutputType.forNumber(outputType_);
      return result == null ? OutputType.CATEGORY_MASK : result;
    }
    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
     * @param value The outputType to set.
     */
    private void setOutputType(OutputType value) {
      outputType_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Optional output mask type.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
     */
    private void clearOutputType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      outputType_ = 1;
    }

    public static final int ACTIVATION_FIELD_NUMBER = 2;
    private int activation_;
    /**
     * <pre>
     * Activation function to apply to input tensor.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
     * @return Whether the activation field is set.
     */
    @Override
    public boolean hasActivation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Activation function to apply to input tensor.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
     * @return The activation.
     */
    @Override
    public Activation getActivation() {
      Activation result = Activation.forNumber(activation_);
      return result == null ? Activation.NONE : result;
    }
    /**
     * <pre>
     * Activation function to apply to input tensor.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
     * @param value The activation to set.
     */
    private void setActivation(Activation value) {
      activation_ = value.getNumber();
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * Activation function to apply to input tensor.
     * </pre>
     *
     * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
     */
    private void clearActivation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      activation_ = 0;
    }

    public static SegmenterOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SegmenterOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SegmenterOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SegmenterOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SegmenterOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SegmenterOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SegmenterOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static SegmenterOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static SegmenterOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static SegmenterOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static SegmenterOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static SegmenterOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(SegmenterOptions prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Shared options used by image segmentation tasks.
     * </pre>
     *
     * Protobuf type {@code mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          SegmenterOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions)
        SegmenterOptionsOrBuilder {
      // Construct using com.google.mediapipe.tasks.vision.imagesegmenter.proto.SegmenterOptionsProto.SegmenterOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Optional output mask type.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
       * @return Whether the outputType field is set.
       */
      @Override
      public boolean hasOutputType() {
        return instance.hasOutputType();
      }
      /**
       * <pre>
       * Optional output mask type.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
       * @return The outputType.
       */
      @Override
      public OutputType getOutputType() {
        return instance.getOutputType();
      }
      /**
       * <pre>
       * Optional output mask type.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
       * @param value The enum numeric value on the wire for outputType to set.
       * @return This builder for chaining.
       */
      public Builder setOutputType(OutputType value) {
        copyOnWrite();
        instance.setOutputType(value);
        return this;
      }
      /**
       * <pre>
       * Optional output mask type.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.OutputType output_type = 1 [default = CATEGORY_MASK];</code>
       * @return This builder for chaining.
       */
      public Builder clearOutputType() {
        copyOnWrite();
        instance.clearOutputType();
        return this;
      }

      /**
       * <pre>
       * Activation function to apply to input tensor.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
       * @return Whether the activation field is set.
       */
      @Override
      public boolean hasActivation() {
        return instance.hasActivation();
      }
      /**
       * <pre>
       * Activation function to apply to input tensor.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
       * @return The activation.
       */
      @Override
      public Activation getActivation() {
        return instance.getActivation();
      }
      /**
       * <pre>
       * Activation function to apply to input tensor.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
       * @param value The enum numeric value on the wire for activation to set.
       * @return This builder for chaining.
       */
      public Builder setActivation(Activation value) {
        copyOnWrite();
        instance.setActivation(value);
        return this;
      }
      /**
       * <pre>
       * Activation function to apply to input tensor.
       * </pre>
       *
       * <code>optional .mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions.Activation activation = 2 [default = NONE];</code>
       * @return This builder for chaining.
       */
      public Builder clearActivation() {
        copyOnWrite();
        instance.clearActivation();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new SegmenterOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "outputType_",
              OutputType.internalGetVerifier(),
              "activation_",
              Activation.internalGetVerifier(),
            };
            String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u100c\u0000\u0002" +
                "\u100c\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<SegmenterOptions> parser = PARSER;
          if (parser == null) {
            synchronized (SegmenterOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<SegmenterOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mediapipe.tasks.vision.image_segmenter.proto.SegmenterOptions)
    private static final SegmenterOptions DEFAULT_INSTANCE;
    static {
      SegmenterOptions defaultInstance = new SegmenterOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SegmenterOptions.class, defaultInstance);
    }

    public static SegmenterOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SegmenterOptions> PARSER;

    public static com.google.protobuf.Parser<SegmenterOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
